const english = {
  title: "Choose your product",
  subtitle: "Your access is checked separately for each WIFIGATE product.",
  eyebrow: "YOUR WIFIGATE WORKSPACE",
  intro:
    "Choose a workspace to continue. Your available products and the next step are shown below.",
  securityIntro:
    "Set up once, then use a short code from your authenticator when you sign in.",
  stepIdentity: "Confirm your identity",
  stepIdentityDetail:
    "Continue with the Google or Apple account you used to sign in.",
  stepPair: "Connect an authenticator",
  stepPairDetail:
    "Scan the QR code and enter the six-digit code from your app.",
  stepContinue: "Open your workspace",
  stepContinueDetail:
    "Verify your sign-in to access the products available to you.",
  readyDetail: "Your access is ready. Open this workspace to continue.",
  setupDetail:
    "Your access is approved. Complete authenticator setup to open this workspace.",
  verifyDetail:
    "Your authenticator is connected. Verify this sign-in to continue.",
  planDetail:
    "This product is not included in your account. Contact us to discuss access.",
  pendingDetail:
    "An administrator needs to approve your access before you can continue.",
  blockedDetail: "Contact your platform administrator to review your access.",
  unavailableDetail:
    "We could not check this product. You can retry without leaving this page.",
  interfaceLanguage: "Interface language",
  checking: "Checking your access...",
  opening: "Opening your dashboard...",
  signingIn: "Signing in...",
  accessUnavailable: "Unable to check access right now. Please try again.",
  retry: "Try again",
  refresh: "Refresh access",
  signOut: "Sign out",
  open: "Open",
  learn: "Learn more",
  contact: "Contact us",
  products: "Products",
  allProducts: "All products",
  security: "Account security",
  optionalSecurity: "You can add an authenticator for extra account security.",
  requiredSecurity:
    "Your role requires an authenticator before you can open this product.",
  unverified: "Sign in with a verified email to access a product.",
  host: "Reservations, rooms and guest access",
  pay: "Paid entry: single entry or timed access",
  manager: "Live management of the gates you administer",
  active: "Active",
  pending: "Waiting for approval",
  "no-plan": "No plan",
  blocked: "Access blocked",
  "mfa-required": "Two-step verification required",
  unavailable: "Temporarily unavailable",
  enroll: "Set up authenticator",
  verify: "Verify authenticator",
  setup: "Confirm identity and start setup",
  confirm: "Confirm your identity in the provider window...",
  setupCode: "Enter the current code to confirm setup.",
  verifySetup: "Verifying setup...",
  setupDone: "Authenticator added. Verify your sign-in to continue.",
  empty: "Your access is active. This product workspace is not available yet.",
  loading: "Checking product access...",
  back: "Back to products",
};

const hebrew = {
  title: "בחירת מוצר",
  subtitle: "הגישה נבדקת בנפרד לכל מוצר של WIFIGATE.",
  eyebrow: "סביבת העבודה שלכם ב־WIFIGATE",
  intro:
    "בחרו סביבת עבודה כדי להמשיך. כאן מוצגים המוצרים הזמינים לכם והצעד הבא לכניסה.",
  securityIntro:
    "מגדירים פעם אחת, ולאחר מכן מאשרים כניסה באמצעות קוד קצר מאפליקציית האימות.",
  stepIdentity: "אימות הזהות",
  stepIdentityDetail: "ממשיכים עם חשבון Google או Apple ששימש להתחברות.",
  stepPair: "חיבור אפליקציית אימות",
  stepPairDetail: "סורקים את קוד ה־QR ומזינים את הקוד בן שש הספרות מהאפליקציה.",
  stepContinue: "כניסה לסביבת העבודה",
  stepContinueDetail: "מאמתים את ההתחברות ונכנסים למוצרים הזמינים לכם.",
  readyDetail: "הגישה שלכם מוכנה. אפשר להיכנס לסביבת העבודה.",
  setupDetail: "הגישה שלכם אושרה. נותר להגדיר אפליקציית אימות כדי להיכנס.",
  verifyDetail: "אפליקציית האימות כבר מחוברת. יש לאמת את ההתחברות כדי להמשיך.",
  planDetail: "המוצר אינו כלול בחשבון שלכם. פנו אלינו לבדיקת אפשרויות הגישה.",
  pendingDetail: "מנהל הפלטפורמה צריך לאשר את הגישה לפני שתוכלו להמשיך.",
  blockedDetail: "פנו למנהל הפלטפורמה לבדיקת הגישה שלכם.",
  unavailableDetail: "לא הצלחנו לבדוק את הגישה למוצר. אפשר לנסות שוב כאן.",
  interfaceLanguage: "שפת הממשק",
  checking: "בודקים את הגישה שלך...",
  opening: "פותחים את לוח הבקרה...",
  signingIn: "מתחברים...",
  accessUnavailable: "לא ניתן לבדוק גישה כרגע. נא לנסות שוב.",
  retry: "ניסיון חוזר",
  refresh: "רענון הגישה",
  signOut: "יציאה",
  open: "פתיחה",
  learn: "מידע נוסף",
  contact: "צרו קשר",
  products: "מוצרים",
  allProducts: "כל המוצרים",
  security: "אבטחת החשבון",
  optionalSecurity: "אפשר להוסיף אפליקציית אימות לאבטחה נוספת של החשבון.",
  requiredSecurity: "התפקיד שלך מחייב אפליקציית אימות לפני פתיחת המוצר.",
  unverified: "יש להיכנס עם כתובת אימייל מאומתת כדי לגשת למוצר.",
  host: "הזמנות, חדרים וגישת אורחים",
  pay: "תשלום על כניסה: כניסה אחת או גישה מתוזמנת",
  manager: "ניהול חי של השערים שאתם מנהלים",
  active: "פעיל",
  pending: "ממתין לאישור",
  "no-plan": "ללא תוכנית",
  blocked: "הגישה חסומה",
  "mfa-required": "נדרש אימות דו־שלבי",
  unavailable: "לא זמין זמנית",
  enroll: "הגדרת אפליקציית אימות",
  verify: "אימות החשבון",
  setup: "אימות זהות והתחלת ההגדרה",
  confirm: "יש לאשר את הזהות בחלון ההתחברות...",
  setupCode: "יש להזין את הקוד הנוכחי כדי לאשר את ההגדרה.",
  verifySetup: "מאמתים את ההגדרה...",
  setupDone: "אפליקציית האימות נוספה. יש לאמת את ההתחברות כדי להמשיך.",
  empty: "הגישה שלך פעילה. סביבת העבודה של המוצר עדיין אינה זמינה.",
  loading: "בודקים את הגישה למוצר...",
  back: "חזרה למוצרים",
};

export function platformText(language = "en") {
  return language === "he" ? hebrew : english;
}
