const english = {
  title: "Choose your product",
  subtitle: "Your access is checked separately for each WIFIGATE product.",
  checking: "Checking your access...",
  opening: "Opening your dashboard...",
  signingIn: "Signing in...",
  accessUnavailable: "Unable to check access right now. Please try again.",
  retry: "Try again",
  refresh: "Refresh access",
  signOut: "Sign out",
  open: "Open",
  learn: "Learn more",
  contact: "Contact us",
  products: "Products",
  allProducts: "All products",
  security: "Account security",
  optionalSecurity: "You can add an authenticator for extra account security.",
  requiredSecurity:
    "Your role requires an authenticator before you can open this product.",
  unverified: "Sign in with a verified email to access a product.",
  host: "Reservations, rooms and guest access",
  pay: "Paid entry: single entry or timed access",
  manager: "Live management of the gates you administer",
  active: "Active",
  pending: "Waiting for approval",
  "no-plan": "No plan",
  blocked: "Access blocked",
  "mfa-required": "Two-step verification required",
  unavailable: "Temporarily unavailable",
  enroll: "Set up authenticator",
  verify: "Verify authenticator",
  setup: "Confirm identity and start setup",
  confirm: "Confirm your identity in the provider window...",
  setupCode: "Enter the current code to confirm setup.",
  verifySetup: "Verifying setup...",
  setupDone: "Authenticator added. Verify your sign-in to continue.",
  empty: "Your access is active. This product workspace is not available yet.",
  loading: "Checking product access...",
  back: "Back to products",
};

const hebrew = {
  title: "בחירת מוצר",
  subtitle: "הגישה נבדקת בנפרד לכל מוצר של WIFIGATE.",
  checking: "בודקים את הגישה שלך...",
  opening: "פותחים את לוח הבקרה...",
  signingIn: "מתחברים...",
  accessUnavailable: "לא ניתן לבדוק גישה כרגע. נא לנסות שוב.",
  retry: "ניסיון חוזר",
  refresh: "רענון הגישה",
  signOut: "יציאה",
  open: "פתיחה",
  learn: "מידע נוסף",
  contact: "צרו קשר",
  products: "מוצרים",
  allProducts: "כל המוצרים",
  security: "אבטחת החשבון",
  optionalSecurity: "אפשר להוסיף אפליקציית אימות לאבטחה נוספת של החשבון.",
  requiredSecurity: "התפקיד שלך מחייב אפליקציית אימות לפני פתיחת המוצר.",
  unverified: "יש להיכנס עם כתובת אימייל מאומתת כדי לגשת למוצר.",
  host: "הזמנות, חדרים וגישת אורחים",
  pay: "תשלום על כניסה: כניסה אחת או גישה מתוזמנת",
  manager: "ניהול חי של השערים שאתם מנהלים",
  active: "פעיל",
  pending: "ממתין לאישור",
  "no-plan": "ללא תוכנית",
  blocked: "הגישה חסומה",
  "mfa-required": "נדרש אימות דו־שלבי",
  unavailable: "לא זמין זמנית",
  enroll: "הגדרת אפליקציית אימות",
  verify: "אימות החשבון",
  setup: "אימות זהות והתחלת ההגדרה",
  confirm: "יש לאשר את הזהות בחלון ההתחברות...",
  setupCode: "יש להזין את הקוד הנוכחי כדי לאשר את ההגדרה.",
  verifySetup: "מאמתים את ההגדרה...",
  setupDone: "אפליקציית האימות נוספה. יש לאמת את ההתחברות כדי להמשיך.",
  empty: "הגישה שלך פעילה. סביבת העבודה של המוצר עדיין אינה זמינה.",
  loading: "בודקים את הגישה למוצר...",
  back: "חזרה למוצרים",
};

export function platformText(language = "en") {
  return language === "he" ? hebrew : english;
}
