// The footer link to the accessibility statement, in every locale.
export const accessibilityLinkLabels = {
  en: "Accessibility Statement",
  he: "הצהרת נגישות",
  es: "Declaración de accesibilidad",
  fr: "Déclaration d'accessibilité",
  de: "Erklärung zur Barrierefreiheit",
  nl: "Toegankelijkheidsverklaring",
  it: "Dichiarazione di accessibilità",
  pt: "Declaração de acessibilidade",
  pl: "Deklaracja dostępności",
  no: "Tilgjengelighetserklæring",
  cs: "Prohlášení o přístupnosti",
  ru: "Заявление о доступности",
  uk: "Заява про доступність",
  tr: "Erişilebilirlik beyanı",
  ar: "بيان إمكانية الوصول",
  hi: "सुलभता विवरण",
  bn: "অভিগম্যতা বিবৃতি",
  mr: "सुलभता निवेदन",
  te: "ప్రాప్యత ప్రకటన",
  "zh-Hans": "无障碍声明",
  "zh-Hant": "無障礙聲明",
  ja: "アクセシビリティ方針",
  ko: "접근성 선언문",
  da: "Tilgængelighedserklæring",
  sv: "Tillgänglighetsredogörelse",
  hu: "Akadálymentességi nyilatkozat",
  el: "Δήλωση προσβασιμότητας",
  ro: "Declarație de accesibilitate",
  hr: "Izjava o pristupačnosti",
  fi: "Saavutettavuusseloste",
  bg: "Декларация за достъпност",
  sr: "Изјава о приступачности",
  sk: "Vyhlásenie o prístupnosti",
  sl: "Izjava o dostopnosti",
  id: "Pernyataan aksesibilitas",
  th: "คำชี้แจงการเข้าถึง",
  vi: "Tuyên bố về khả năng tiếp cận",
  ms: "Pernyataan kebolehcapaian",
  fil: "Pahayag sa accessibility",
};
