// Sign-in page copy (/ar/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "تسجيل الدخول",
  heading: "تسجيل الدخول إلى WIFIGATE",
  home: "الصفحة الرئيسية لـ WIFIGATE",
  google: "المتابعة باستخدام Google",
  apple: "المتابعة باستخدام Apple",
  signingInLabel: "جارٍ تسجيل الدخول",
  legal: "بالمتابعة، فإنك توافق على {terms} و{privacy}.",
  terms: "الشروط",
  privacy: "سياسة الخصوصية",
  chooseLanguage: "اختر اللغة",
  close: "إغلاق",
  stagingTitle: "بيئة اختبار محلية",
  stagingText: "يتم استخدام حسابات Google أو Apple وهمية. لا حاجة إلى كلمة مرور المزوّد.",
  mfaTitle: "التحقق باستخدام تطبيق المصادقة",
  mfaText: "أدخل الرمز الحالي من تطبيق المصادقة لإكمال تسجيل الدخول.",
  mfaFactor: "تطبيق المصادقة",
  mfaCode: "رمز التحقق",
  mfaVerify: "تحقق",
  mfaCancel: "إلغاء",
  mfaHelp: "فقدت إمكانية الوصول؟ تواصل مع مسؤول المنصة للتحقق من هويتك واستعادة وسيلة المصادقة.",
  authenticatorN: "تطبيق المصادقة {n}",
  verifying: "جارٍ التحقق...",
  checking: "جارٍ التحقق من صلاحية وصولك...",
  opening: "جارٍ فتح لوحة التحكم...",
  signingIn: "جارٍ تسجيل الدخول...",
  humanReady: "تم اجتياز التحقق. يمكنك الآن المتابعة باستخدام Google أو Apple.",
  accessUnavailable: "يتعذر التحقق من الوصول حاليًا. يُرجى المحاولة مرة أخرى.",
  gameTitle: "أنا لست برنامج روبوت",
  gameInstruction: "للتأكيد، اسحب السيارة إلى البوابة المفتوحة",
  gameFooter: "التحقق البشري · WIFIGATE",
  gameKeyboard: "السيارة في المسار {lane} من 3. تغيّر الأسهم المسار، ويقود Enter السيارة.",
  gameGate: "البوابة {n}، {state}",
  gateOpen: "مفتوحة",
  gateClosed: "مغلقة",
  gameRetry: "ليس تمامًا. ادخل البوابة الخضراء.",
  gameLocked: "محاولات كثيرة جدًا. حاول مرة أخرى بعد {s} ثانية.",
  gameDone: "تم التحقق. أنت لست روبوتًا.",
  errorCancelled: "تم إلغاء تسجيل الدخول.",
  errorPopupBlocked: "حظر المتصفح نافذة تسجيل الدخول.",
  errorInvalidCode: "الرمز غير صحيح أو انتهت صلاحيته.",
  errorMissingCode: "أدخل الرمز من تطبيق المصادقة.",
  errorNetwork: "يتعذر الاتصال. تحقق من اتصالك بالشبكة.",
  errorMfaCancelled: "تم إلغاء التحقق من الحساب.",
  errorMfaUnsupported: "لا يوجد تطبيق مصادقة مدعوم في هذا الحساب.",
  errorUnverifiedEmail: "استخدم البريد الإلكتروني الموثّق الذي وافق عليه المسؤول.",
  errorUnconfigured: "إعدادات تسجيل الدخول مفقودة. يُرجى التواصل مع الدعم.",
  errorServer: "يتعذر الاتصال بخادم WIFIGATE. يُرجى المحاولة مرة أخرى.",
  errorSessionExpired: "انتهت صلاحية الجلسة. سجّل الدخول مرة أخرى.",
  errorForbidden: "الوصول غير مسموح به. تواصل مع مسؤول النظام.",
  errorGeneric: "حدث خطأ ما. يُرجى المحاولة مرة أخرى.",
};
