// Sign-in page copy (/cs/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Přihlášení",
  heading: "Přihlášení do WIFIGATE",
  home: "Domovská stránka WIFIGATE",
  google: "Pokračovat přes Google",
  apple: "Pokračovat přes Apple",
  signingInLabel: "Přihlašování",
  legal: "Pokračováním souhlasíte s dokumenty {terms} a {privacy}.",
  terms: "Podmínky použití",
  privacy: "Zásady ochrany osobních údajů",
  chooseLanguage: "Vyberte jazyk",
  close: "Zavřít",
  stagingTitle: "Místní testovací prostředí",
  stagingText: "Používáte simulované účty Google nebo Apple. Heslo poskytovatele není potřeba.",
  mfaTitle: "Ověření pomocí ověřovací aplikace",
  mfaText: "Zadejte aktuální kód z ověřovací aplikace a dokončete přihlášení.",
  mfaFactor: "Ověřovací aplikace",
  mfaCode: "Ověřovací kód",
  mfaVerify: "Ověřit",
  mfaCancel: "Zrušit",
  mfaHelp: "Ztratili jste přístup? Obraťte se na správce platformy, který ověří vaši totožnost a obnoví metodu ověření.",
  authenticatorN: "Ověřovací aplikace {n}",
  verifying: "Ověřování...",
  checking: "Kontrolujeme váš přístup...",
  opening: "Otevíráme ovládací panel...",
  signingIn: "Přihlašování...",
  humanReady: "Hotovo. Nyní můžete pokračovat přes Google nebo Apple.",
  accessUnavailable: "Přístup teď nelze ověřit. Zkuste to prosím znovu.",
  gameTitle: "Nejsem robot",
  gameInstruction: "Pro potvrzení přetáhněte auto do otevřené brány",
  gameFooter: "Ověření člověka · WIFIGATE",
  gameKeyboard: "Auto v pruhu {lane} ze 3. Šipky mění pruh, Enter jede.",
  gameGate: "Brána {n}, {state}",
  gateOpen: "otevřená",
  gateClosed: "zavřená",
  gameRetry: "Skoro. Vjeďte do zelené brány.",
  gameLocked: "Příliš mnoho pokusů. Zkuste to znovu za {s} s.",
  gameDone: "Ověřeno. Nejste robot.",
  errorCancelled: "Přihlášení bylo zrušeno.",
  errorPopupBlocked: "Prohlížeč zablokoval přihlašovací okno.",
  errorInvalidCode: "Kód je nesprávný nebo vypršel.",
  errorMissingCode: "Zadejte kód z ověřovací aplikace.",
  errorNetwork: "Nelze se připojit. Zkontrolujte připojení k síti.",
  errorMfaCancelled: "Ověření účtu bylo zrušeno.",
  errorMfaUnsupported: "Tento účet nemá žádnou podporovanou ověřovací aplikaci.",
  errorUnverifiedEmail: "Použijte ověřený e-mail schválený správcem.",
  errorUnconfigured: "Chybí nastavení přihlášení. Obraťte se na podporu.",
  errorServer: "Server WIFIGATE není dostupný. Zkuste to prosím znovu.",
  errorSessionExpired: "Platnost přihlášení vypršela. Přihlaste se znovu.",
  errorForbidden: "Přístup není povolen. Obraťte se na správce systému.",
  errorGeneric: "Něco se pokazilo. Zkuste to prosím znovu.",
};
