// Sign-in page copy (/da/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Log ind",
  heading: "Log ind på WIFIGATE",
  home: "WIFIGATE-forside",
  google: "Fortsæt med Google",
  apple: "Fortsæt med Apple",
  signingInLabel: "Logger ind",
  legal: "Ved at fortsætte accepterer du vores {terms} og vores {privacy}.",
  terms: "vilkår",
  privacy: "privatlivspolitik",
  chooseLanguage: "Vælg sprog",
  close: "Luk",
  stagingTitle: "Lokalt testmiljø",
  stagingText: "Brug fiktive Google- eller Apple-konti. Der kræves ingen adgangskode fra udbyderen.",
  mfaTitle: "Bekræft med godkendelsesappen",
  mfaText: "Indtast den aktuelle kode fra din godkendelsesapp for at fuldføre login.",
  mfaFactor: "Godkendelsesapp",
  mfaCode: "Bekræftelseskode",
  mfaVerify: "Bekræft",
  mfaCancel: "Annuller",
  mfaHelp: "Mistet adgangen? Kontakt platformens administrator for at bekræfte din identitet og gendanne din godkendelsesmetode.",
  authenticatorN: "Godkendelsesapp {n}",
  verifying: "Bekræfter...",
  checking: "Tjekker din adgang...",
  opening: "Åbner kontrolpanelet...",
  signingIn: "Logger ind...",
  humanReady: "Du bestod. Fortsæt nu med Google eller Apple.",
  accessUnavailable: "Adgangen kan ikke tjekkes lige nu. Prøv igen.",
  gameTitle: "Jeg er ikke en robot",
  gameInstruction: "Bekræft ved at trække bilen ind i den åbne port",
  gameFooter: "Menneskekontrol · WIFIGATE",
  gameKeyboard: "Bilen er i vognbane {lane} af 3. Piletasterne skifter vognbane, Enter kører.",
  gameGate: "Port {n}, {state}",
  gateOpen: "åben",
  gateClosed: "lukket",
  gameRetry: "Ikke helt. Kør ind i den grønne port.",
  gameLocked: "For mange forsøg. Prøv igen om {s} sekunder.",
  gameDone: "Bekræftet. Du er ikke en robot.",
  errorCancelled: "Login blev annulleret.",
  errorPopupBlocked: "Browseren blokerede loginvinduet.",
  errorInvalidCode: "Koden er forkert eller udløbet.",
  errorMissingCode: "Indtast koden fra din godkendelsesapp.",
  errorNetwork: "Der kan ikke oprettes forbindelse. Tjek din netværksforbindelse.",
  errorMfaCancelled: "Bekræftelsen af kontoen blev annulleret.",
  errorMfaUnsupported: "Denne konto har ingen understøttet godkendelsesapp.",
  errorUnverifiedEmail: "Brug den bekræftede e-mailadresse, som din administrator har godkendt.",
  errorUnconfigured: "Loginindstillingerne mangler. Kontakt kundeservice.",
  errorServer: "Kan ikke oprette forbindelse til WIFIGATE-serveren. Prøv igen.",
  errorSessionExpired: "Dit login er udløbet. Log ind igen.",
  errorForbidden: "Adgang nægtet. Kontakt systemadministratoren.",
  errorGeneric: "Noget gik galt. Prøv igen.",
};
