// Sign-in page copy (/de/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Anmelden",
  heading: "Bei WIFIGATE anmelden",
  home: "WIFIGATE-Startseite",
  google: "Weiter mit Google",
  apple: "Mit Apple fortfahren",
  signingInLabel: "Anmeldung läuft",
  legal: "Wenn du fortfährst, stimmst du den {terms} und der {privacy} zu.",
  terms: "Nutzungsbedingungen",
  privacy: "Datenschutzerklärung",
  chooseLanguage: "Sprache wählen",
  close: "Schließen",
  stagingTitle: "Lokale Testumgebung",
  stagingText: "Verwende simulierte Google- oder Apple-Konten. Ein Passwort des Anbieters ist nicht nötig.",
  mfaTitle: "Bestätigung per Authentifizierungs-App",
  mfaText: "Gib den aktuellen Code aus deiner Authentifizierungs-App ein, um die Anmeldung abzuschließen.",
  mfaFactor: "Authentifizierungs-App",
  mfaCode: "Bestätigungscode",
  mfaVerify: "Bestätigen",
  mfaCancel: "Abbrechen",
  mfaHelp: "Kein Zugriff mehr? Wende dich an den Plattformadministrator, um deine Identität zu bestätigen und deine Authentifizierungsmethode wiederherzustellen.",
  authenticatorN: "Authentifizierungs-App {n}",
  verifying: "Wird bestätigt...",
  checking: "Dein Zugriff wird geprüft...",
  opening: "Dashboard wird geöffnet...",
  signingIn: "Anmeldung...",
  humanReady: "Bestanden. Jetzt kannst du mit Google oder Apple fortfahren.",
  accessUnavailable: "Der Zugriff kann gerade nicht geprüft werden. Bitte versuche es erneut.",
  gameTitle: "Ich bin kein Roboter",
  gameInstruction: "Zieh zur Bestätigung das Auto in das offene Tor",
  gameFooter: "Menschlichkeitsprüfung · WIFIGATE",
  gameKeyboard: "Auto auf Spur {lane} von 3. Pfeiltasten wechseln die Spur, Enter fährt los.",
  gameGate: "Tor {n}, {state}",
  gateOpen: "offen",
  gateClosed: "geschlossen",
  gameRetry: "Nicht ganz. Fahr in das grüne Tor.",
  gameLocked: "Zu viele Versuche. Versuche es in {s} Sekunden erneut.",
  gameDone: "Bestätigt. Du bist kein Roboter.",
  errorCancelled: "Die Anmeldung wurde abgebrochen.",
  errorPopupBlocked: "Dein Browser hat das Anmeldefenster blockiert.",
  errorInvalidCode: "Der Code ist falsch oder abgelaufen.",
  errorMissingCode: "Gib den Code aus deiner Authentifizierungs-App ein.",
  errorNetwork: "Verbindung nicht möglich. Prüfe deine Netzwerkverbindung.",
  errorMfaCancelled: "Die Kontobestätigung wurde abgebrochen.",
  errorMfaUnsupported: "Für dieses Konto ist keine unterstützte Authentifizierungs-App eingerichtet.",
  errorUnverifiedEmail: "Verwende die bestätigte E-Mail-Adresse, die dein Administrator freigegeben hat.",
  errorUnconfigured: "Die Anmeldeeinstellungen fehlen. Bitte wende dich an den Support.",
  errorServer: "Der WIFIGATE-Server ist nicht erreichbar. Bitte versuche es erneut.",
  errorSessionExpired: "Deine Sitzung ist abgelaufen. Melde dich erneut an.",
  errorForbidden: "Zugriff nicht gestattet. Wende dich an den Systemadministrator.",
  errorGeneric: "Etwas ist schiefgelaufen. Bitte versuche es erneut.",
};
