// Sign-in page copy (/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Sign in",
  heading: "Sign in to WIFIGATE",
  home: "WIFIGATE home",
  google: "Continue with Google",
  apple: "Continue with Apple",
  signingInLabel: "Signing in",
  legal: "By continuing you agree to the {terms} and {privacy}.",
  terms: "Terms",
  privacy: "Privacy Policy",
  chooseLanguage: "Choose your language",
  close: "Close",
  stagingTitle: "Local test environment",
  stagingText: "Use mock Google or Apple accounts. No provider password is needed.",
  mfaTitle: "Verify your authenticator",
  mfaText: "Enter the current code from your authenticator app to finish signing in.",
  mfaFactor: "Authenticator",
  mfaCode: "Verification code",
  mfaVerify: "Verify",
  mfaCancel: "Cancel",
  mfaHelp: "Lost access? Contact a platform owner to verify your identity and recover your factor.",
  authenticatorN: "Authenticator {n}",
  verifying: "Verifying...",
  checking: "Checking your access...",
  opening: "Opening your dashboard...",
  signingIn: "Signing in...",
  humanReady: "You passed. Now continue with Google or Apple.",
  accessUnavailable: "Unable to check access right now. Please try again.",
  gameTitle: "I'm not a robot",
  gameInstruction: "To confirm, drag the car into the open gate",
  gameFooter: "Human check · WIFIGATE",
  gameKeyboard: "Car in lane {lane} of 3. Arrow keys change lane, Enter drives.",
  gameGate: "Gate {n}, {state}",
  gateOpen: "open",
  gateClosed: "closed",
  gameRetry: "Not quite. Drive into the green gate.",
  gameLocked: "Too many tries. Try again in {s} s.",
  gameDone: "Verified. You're not a robot.",
  errorCancelled: "Sign-in was cancelled.",
  errorPopupBlocked: "Your browser blocked the sign-in window.",
  errorInvalidCode: "That code is incorrect or expired.",
  errorMissingCode: "Enter the code from your authenticator app.",
  errorNetwork: "Unable to connect. Check your connection.",
  errorMfaCancelled: "Authenticator verification was cancelled.",
  errorMfaUnsupported: "No supported authenticator on this account.",
  errorUnverifiedEmail: "Use the verified email approved by your admin.",
  errorUnconfigured: "Sign-in settings are missing. Contact support.",
  errorServer: "Cannot reach the WIFIGATE server. Please try again.",
  errorSessionExpired: "Your session expired. Sign in again.",
  errorForbidden: "Access was not permitted. Contact your admin.",
  errorGeneric: "Something went wrong. Please try again.",
};
