// Sign-in page copy (/es/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Iniciar sesión",
  heading: "Inicia sesión en WIFIGATE",
  home: "Página de inicio de WIFIGATE",
  google: "Continuar con Google",
  apple: "Continuar con Apple",
  signingInLabel: "Iniciando sesión",
  legal: "Al continuar, aceptas los {terms} y la {privacy}.",
  terms: "Términos",
  privacy: "Política de privacidad",
  chooseLanguage: "Elige un idioma",
  close: "Cerrar",
  stagingTitle: "Entorno de pruebas local",
  stagingText: "Usa cuentas simuladas de Google o Apple. No necesitas la contraseña del proveedor.",
  mfaTitle: "Verificación con la app de autenticación",
  mfaText: "Introduce el código actual de tu app de autenticación para completar el inicio de sesión.",
  mfaFactor: "App de autenticación",
  mfaCode: "Código de verificación",
  mfaVerify: "Verificar",
  mfaCancel: "Cancelar",
  mfaHelp: "¿Perdiste el acceso? Contacta con el administrador de la plataforma para verificar tu identidad y recuperar tu método de verificación.",
  authenticatorN: "App de autenticación {n}",
  verifying: "Verificando...",
  checking: "Comprobando tu acceso...",
  opening: "Abriendo el panel de control...",
  signingIn: "Iniciando sesión...",
  humanReady: "Superado. Ahora puedes continuar con Google o Apple.",
  accessUnavailable: "No se puede comprobar el acceso en este momento. Inténtalo de nuevo.",
  gameTitle: "No soy un robot",
  gameInstruction: "Para confirmar, arrastra el coche hasta la puerta abierta",
  gameFooter: "Verificación humana · WIFIGATE",
  gameKeyboard: "El coche está en el carril {lane} de 3. Las flechas cambian de carril y Enter avanza.",
  gameGate: "Puerta {n}, {state}",
  gateOpen: "abierta",
  gateClosed: "cerrada",
  gameRetry: "Casi. Entra por la puerta verde.",
  gameLocked: "Demasiados intentos. Vuelve a intentarlo en {s} segundos.",
  gameDone: "Verificado. No eres un robot.",
  errorCancelled: "Se canceló el inicio de sesión.",
  errorPopupBlocked: "El navegador bloqueó la ventana de inicio de sesión.",
  errorInvalidCode: "El código es incorrecto o ha caducado.",
  errorMissingCode: "Introduce el código de tu app de autenticación.",
  errorNetwork: "No se puede conectar. Comprueba tu conexión a la red.",
  errorMfaCancelled: "Se canceló la verificación de la cuenta.",
  errorMfaUnsupported: "Esta cuenta no tiene ninguna app de autenticación compatible.",
  errorUnverifiedEmail: "Usa el correo electrónico verificado que aprobó el administrador.",
  errorUnconfigured: "Falta la configuración de inicio de sesión. Contacta con el soporte.",
  errorServer: "No se puede conectar con el servidor de WIFIGATE. Inténtalo de nuevo.",
  errorSessionExpired: "La sesión ha caducado. Vuelve a iniciar sesión.",
  errorForbidden: "Acceso no autorizado. Contacta con el administrador del sistema.",
  errorGeneric: "Algo salió mal. Inténtalo de nuevo.",
};
