// Sign-in page copy (/fi/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Kirjaudu sisään",
  heading: "Kirjaudu WIFIGATE-palveluun",
  home: "WIFIGATE-etusivu",
  google: "Jatka Googlella",
  apple: "Jatka Applella",
  signingInLabel: "Kirjaudutaan",
  legal: "Jatkamalla hyväksyt seuraavat: {terms} ja {privacy}.",
  terms: "Käyttöehdot",
  privacy: "Tietosuojakäytäntö",
  chooseLanguage: "Valitse kieli",
  close: "Sulje",
  stagingTitle: "Paikallinen testiympäristö",
  stagingText: "Käytössä ovat simuloidut Google- tai Apple-tilit. Palveluntarjoajan salasanaa ei tarvita.",
  mfaTitle: "Vahvista todennussovelluksella",
  mfaText: "Viimeistele kirjautuminen syöttämällä todennussovelluksen nykyinen koodi.",
  mfaFactor: "Todennussovellus",
  mfaCode: "Vahvistuskoodi",
  mfaVerify: "Vahvista",
  mfaCancel: "Peruuta",
  mfaHelp: "Menetitkö käyttöoikeuden? Ota yhteyttä alustan ylläpitäjään henkilöllisyytesi vahvistamiseksi ja todennustavan palauttamiseksi.",
  authenticatorN: "Todennussovellus {n}",
  verifying: "Vahvistetaan...",
  checking: "Tarkistetaan käyttöoikeuttasi...",
  opening: "Avataan hallintapaneelia...",
  signingIn: "Kirjaudutaan sisään...",
  humanReady: "Läpäisit tarkistuksen. Jatka nyt Googlella tai Applella.",
  accessUnavailable: "Käyttöoikeutta ei voi tarkistaa juuri nyt. Yritä uudelleen.",
  gameTitle: "En ole robotti",
  gameInstruction: "Vahvista vetämällä auto avoimeen porttiin",
  gameFooter: "Ihmistarkistus · WIFIGATE",
  gameKeyboard: "Auto on kaistalla {lane}/3. Nuolinäppäimet vaihtavat kaistaa, Enter ajaa.",
  gameGate: "Portti {n}, {state}",
  gateOpen: "auki",
  gateClosed: "kiinni",
  gameRetry: "Melkein. Aja vihreään porttiin.",
  gameLocked: "Liian monta yritystä. Yritä uudelleen {s} sekunnin kuluttua.",
  gameDone: "Vahvistettu. Et ole robotti.",
  errorCancelled: "Kirjautuminen peruutettiin.",
  errorPopupBlocked: "Selain esti kirjautumisikkunan.",
  errorInvalidCode: "Koodi on virheellinen tai vanhentunut.",
  errorMissingCode: "Syötä todennussovelluksen koodi.",
  errorNetwork: "Yhteyttä ei voi muodostaa. Tarkista verkkoyhteys.",
  errorMfaCancelled: "Tilin vahvistus peruutettiin.",
  errorMfaUnsupported: "Tällä tilillä ei ole tuettua todennussovellusta.",
  errorUnverifiedEmail: "Käytä järjestelmänvalvojan hyväksymää vahvistettua sähköpostiosoitetta.",
  errorUnconfigured: "Kirjautumisasetukset puuttuvat. Ota yhteyttä tukeen.",
  errorServer: "WIFIGATE-palvelimeen ei saada yhteyttä. Yritä uudelleen.",
  errorSessionExpired: "Kirjautuminen vanheni. Kirjaudu uudelleen.",
  errorForbidden: "Käyttö ei ole sallittu. Ota yhteyttä järjestelmänvalvojaan.",
  errorGeneric: "Jokin meni vikaan. Yritä uudelleen.",
};
