// Sign-in page copy (/fil/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Pumasok",
  heading: "Pumasok sa WIFIGATE",
  home: "Pangunahing pahina ng WIFIGATE",
  google: "Magpatuloy gamit ang Google",
  apple: "Magpatuloy gamit ang Apple",
  signingInLabel: "Pumapasok",
  legal: "Sa pagpapatuloy, sumasang-ayon ka sa {terms} at {privacy}.",
  terms: "Mga Tuntunin",
  privacy: "Patakaran sa Pagkapribado",
  chooseLanguage: "Pumili ng wika",
  close: "Isara",
  stagingTitle: "Lokal na pansubok na kapaligiran",
  stagingText: "Gumagamit ng kunwaring akawnt ng Google o Apple. Hindi kailangan ang password ng tagapagbigay.",
  mfaTitle: "Pagpapatunay gamit ang aplikasyong pampatunay",
  mfaText: "Ilagay ang kasalukuyang kodigo mula sa aplikasyong pampatunay para matapos ang pagpasok.",
  mfaFactor: "Aplikasyong pampatunay",
  mfaCode: "Kodigo ng pagpapatunay",
  mfaVerify: "Patunayan",
  mfaCancel: "Kanselahin",
  mfaHelp: "Hindi na makapasok? Makipag-ugnayan sa tagapangasiwa ng plataporma para mapatunayan ang iyong pagkakakilanlan at maibalik ang iyong paraan ng pagpapatunay.",
  authenticatorN: "Aplikasyong pampatunay {n}",
  verifying: "Pinapatunayan...",
  checking: "Sinusuri ang iyong pahintulot na makapasok...",
  opening: "Binubuksan ang iyong panel ng kontrol...",
  signingIn: "Pumapasok...",
  humanReady: "Pumasa ka. Magpatuloy na gamit ang Google o Apple.",
  accessUnavailable: "Hindi masuri ang pahintulot sa ngayon. Pakisubukang muli.",
  gameTitle: "Hindi ako robot",
  gameInstruction: "Para kumpirmahin, hilahin ang sasakyan papasok sa bukas na tarangkahan",
  gameFooter: "Pagsusuri kung tao · WIFIGATE",
  gameKeyboard: "Nasa linya {lane} sa 3 ang sasakyan. Palitan ang linya gamit ang mga palaso, pindutin ang Enter para umandar.",
  gameGate: "Tarangkahan {n}, {state}",
  gateOpen: "bukas",
  gateClosed: "sarado",
  gameRetry: "Hindi pa. Pumasok sa berdeng tarangkahan.",
  gameLocked: "Masyadong maraming pagsubok. Subukang muli pagkalipas ng {s} segundo.",
  gameDone: "Napatunayan. Hindi ka robot.",
  errorCancelled: "Kinansela ang pagpasok.",
  errorPopupBlocked: "Hinarang ng iyong pambasang-web ang bintana ng pagpasok.",
  errorInvalidCode: "Mali o paso na ang kodigo.",
  errorMissingCode: "Ilagay ang kodigo mula sa aplikasyong pampatunay.",
  errorNetwork: "Hindi makakonekta. Suriin ang iyong koneksyon.",
  errorMfaCancelled: "Kinansela ang pagpapatunay ng akawnt.",
  errorMfaUnsupported: "Walang suportadong aplikasyong pampatunay ang akawnt na ito.",
  errorUnverifiedEmail: "Gamitin ang napatunayang email na inaprubahan ng tagapangasiwa.",
  errorUnconfigured: "Kulang ang mga pagsasaayos ng pagpasok. Makipag-ugnayan sa suporta.",
  errorServer: "Hindi maabot ang serbidor ng WIFIGATE. Pakisubukang muli.",
  errorSessionExpired: "Natapos na ang iyong sesyon. Pumasok muli.",
  errorForbidden: "Hindi pinahintulutan ang pagpasok. Makipag-ugnayan sa tagapangasiwa ng sistema.",
  errorGeneric: "May nangyaring mali. Pakisubukang muli.",
};
