// Sign-in page copy (/fr/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Connexion",
  heading: "Connexion à WIFIGATE",
  home: "Page d'accueil de WIFIGATE",
  google: "Continuer avec Google",
  apple: "Continuer avec Apple",
  signingInLabel: "Connexion en cours",
  legal: "En continuant, vous acceptez les {terms} et la {privacy}.",
  terms: "Conditions d'utilisation",
  privacy: "Politique de confidentialité",
  chooseLanguage: "Choisir la langue",
  close: "Fermer",
  stagingTitle: "Environnement de test local",
  stagingText: "Utilisez des comptes Google ou Apple fictifs. Aucun mot de passe du fournisseur n'est nécessaire.",
  mfaTitle: "Vérification par application d'authentification",
  mfaText: "Saisissez le code actuel de votre application d'authentification pour terminer la connexion.",
  mfaFactor: "Application d'authentification",
  mfaCode: "Code de vérification",
  mfaVerify: "Vérifier",
  mfaCancel: "Annuler",
  mfaHelp: "Accès perdu ? Contactez l'administrateur de la plateforme pour vérifier votre identité et récupérer votre méthode d'authentification.",
  authenticatorN: "Application d'authentification {n}",
  verifying: "Vérification...",
  checking: "Vérification de votre accès...",
  opening: "Ouverture du tableau de bord...",
  signingIn: "Connexion...",
  humanReady: "Réussi. Vous pouvez maintenant continuer avec Google ou Apple.",
  accessUnavailable: "Impossible de vérifier l'accès pour le moment. Veuillez réessayer.",
  gameTitle: "Je ne suis pas un robot",
  gameInstruction: "Pour confirmer, faites glisser la voiture jusqu'au portail ouvert",
  gameFooter: "Vérification humaine · WIFIGATE",
  gameKeyboard: "Voiture sur la voie {lane} sur 3. Les flèches changent de voie, Enter fait avancer.",
  gameGate: "Portail {n}, {state}",
  gateOpen: "ouvert",
  gateClosed: "fermé",
  gameRetry: "Pas tout à fait. Entrez par le portail vert.",
  gameLocked: "Trop de tentatives. Réessayez dans {s} secondes.",
  gameDone: "Vérifié. Vous n'êtes pas un robot.",
  errorCancelled: "La connexion a été annulée.",
  errorPopupBlocked: "Le navigateur a bloqué la fenêtre de connexion.",
  errorInvalidCode: "Le code est incorrect ou a expiré.",
  errorMissingCode: "Saisissez le code de votre application d'authentification.",
  errorNetwork: "Connexion impossible. Vérifiez votre connexion réseau.",
  errorMfaCancelled: "La vérification du compte a été annulée.",
  errorMfaUnsupported: "Ce compte n'a aucune application d'authentification compatible.",
  errorUnverifiedEmail: "Utilisez l'adresse e-mail vérifiée approuvée par l'administrateur.",
  errorUnconfigured: "Les paramètres de connexion sont manquants. Contactez l'assistance.",
  errorServer: "Impossible de joindre le serveur WIFIGATE. Veuillez réessayer.",
  errorSessionExpired: "La session a expiré. Reconnectez-vous.",
  errorForbidden: "Accès non autorisé. Contactez l'administrateur du système.",
  errorGeneric: "Un problème est survenu. Veuillez réessayer.",
};
