// Sign-in page copy (/he/login/). Hebrew is the source: every other locale
// file has the same keys. {placeholders} stay as they are.
export default {
  pageTitle: "כניסה",
  heading: "כניסה ל־WIFIGATE",
  home: "דף הבית של WIFIGATE",
  google: "המשך עם Google",
  apple: "המשך עם Apple",
  signingInLabel: "מתחברים",
  legal: "בהמשך אתם מסכימים ל{terms} ול{privacy}.",
  terms: "תנאים",
  privacy: "מדיניות הפרטיות",
  chooseLanguage: "בחר שפה",
  close: "סגירה",
  stagingTitle: "סביבת בדיקה מקומית",
  stagingText: "משתמשים בחשבונות Google או Apple מדומים. אין צורך בסיסמה של הספק.",
  mfaTitle: "אימות באמצעות אפליקציית האימות",
  mfaText: "יש להזין את הקוד הנוכחי מאפליקציית האימות כדי להשלים את ההתחברות.",
  mfaFactor: "אפליקציית אימות",
  mfaCode: "קוד אימות",
  mfaVerify: "אימות",
  mfaCancel: "ביטול",
  mfaHelp: "איבדתם גישה? פנו למנהל הפלטפורמה לאימות זהות ושחזור אמצעי האימות.",
  authenticatorN: "אפליקציית אימות {n}",
  verifying: "מאמתים...",
  checking: "בודקים את הגישה שלך...",
  opening: "פותחים את לוח הבקרה...",
  signingIn: "מתחברים...",
  humanReady: "עברתם. עכשיו אפשר להמשיך עם Google או Apple.",
  accessUnavailable: "לא ניתן לבדוק גישה כרגע. נא לנסות שוב.",
  gameTitle: "אני לא רובוט",
  gameInstruction: "כדי לאשר, גררו את המכונית לשער הפתוח",
  gameFooter: "בדיקת אנושיות · WIFIGATE",
  gameKeyboard: "המכונית בנתיב {lane} מתוך 3. החיצים מחליפים נתיב, Enter נוסע.",
  gameGate: "שער {n}, {state}",
  gateOpen: "פתוח",
  gateClosed: "סגור",
  gameRetry: "לא בדיוק. היכנסו לשער הירוק.",
  gameLocked: "יותר מדי ניסיונות. נסו שוב בעוד {s} שניות.",
  gameDone: "אומת. אתם לא רובוט.",
  errorCancelled: "ההתחברות בוטלה.",
  errorPopupBlocked: "הדפדפן חסם את חלון ההתחברות.",
  errorInvalidCode: "הקוד שגוי או שפג תוקפו.",
  errorMissingCode: "יש להזין את הקוד מאפליקציית האימות.",
  errorNetwork: "לא ניתן להתחבר. יש לבדוק את החיבור לרשת.",
  errorMfaCancelled: "אימות החשבון בוטל.",
  errorMfaUnsupported: "אין בחשבון הזה אפליקציית אימות נתמכת.",
  errorUnverifiedEmail: "יש להשתמש באימייל המאומת שאושר על ידי המנהל.",
  errorUnconfigured: "הגדרות ההתחברות חסרות. נא לפנות לתמיכה.",
  errorServer: "לא ניתן להתחבר לשרת WIFIGATE. נא לנסות שוב.",
  errorSessionExpired: "פג תוקף ההתחברות. יש להתחבר שוב.",
  errorForbidden: "הגישה אינה מורשית. יש לפנות למנהל המערכת.",
  errorGeneric: "משהו השתבש. נא לנסות שוב.",
};
