// Sign-in page copy (/hi/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "साइन इन",
  heading: "WIFIGATE में साइन इन करें",
  home: "WIFIGATE होम पेज",
  google: "Google के साथ जारी रखें",
  apple: "Apple के साथ जारी रखें",
  signingInLabel: "साइन इन हो रहा है",
  legal: "जारी रखकर, आप {terms} और {privacy} से सहमत होते हैं।",
  terms: "शर्तें",
  privacy: "निजता नीति",
  chooseLanguage: "भाषा चुनें",
  close: "बंद करें",
  stagingTitle: "स्थानीय परीक्षण परिवेश",
  stagingText: "नकली Google या Apple खातों का उपयोग किया जाता है। प्रदाता के पासवर्ड की ज़रूरत नहीं है।",
  mfaTitle: "ऑथेंटिकेटर ऐप से सत्यापन",
  mfaText: "साइन इन पूरा करने के लिए अपने ऑथेंटिकेटर ऐप का मौजूदा कोड डालें।",
  mfaFactor: "ऑथेंटिकेटर ऐप",
  mfaCode: "सत्यापन कोड",
  mfaVerify: "सत्यापित करें",
  mfaCancel: "रद्द करें",
  mfaHelp: "ऐक्सेस खो दिया? पहचान सत्यापित करने और सत्यापन का तरीका वापस पाने के लिए प्लैटफ़ॉर्म एडमिन से संपर्क करें।",
  authenticatorN: "ऑथेंटिकेटर ऐप {n}",
  verifying: "सत्यापित किया जा रहा है...",
  checking: "आपका ऐक्सेस जांचा जा रहा है...",
  opening: "डैशबोर्ड खोला जा रहा है...",
  signingIn: "साइन इन हो रहा है...",
  humanReady: "आप पास हो गए। अब Google या Apple के साथ जारी रखें।",
  accessUnavailable: "अभी ऐक्सेस की जांच नहीं हो पा रही है। कृपया फिर से कोशिश करें।",
  gameTitle: "मैं रोबोट नहीं हूं",
  gameInstruction: "पुष्टि करने के लिए, कार को खुले गेट तक खींचें",
  gameFooter: "इंसान होने की जांच · WIFIGATE",
  gameKeyboard: "कार 3 में से लेन {lane} में है। तीर कुंजियां लेन बदलती हैं, Enter से कार चलती है।",
  gameGate: "गेट {n}, {state}",
  gateOpen: "खुला",
  gateClosed: "बंद",
  gameRetry: "थोड़ा चूक गए। हरे गेट में जाएं।",
  gameLocked: "बहुत ज़्यादा कोशिशें। {s} सेकंड बाद फिर से कोशिश करें।",
  gameDone: "सत्यापित। आप रोबोट नहीं हैं।",
  errorCancelled: "साइन इन रद्द कर दिया गया।",
  errorPopupBlocked: "ब्राउज़र ने साइन इन विंडो ब्लॉक कर दी।",
  errorInvalidCode: "कोड गलत है या उसकी समय-सीमा खत्म हो गई है।",
  errorMissingCode: "अपने ऑथेंटिकेटर ऐप का कोड डालें।",
  errorNetwork: "कनेक्ट नहीं हो पा रहा है। अपना नेटवर्क कनेक्शन जांचें।",
  errorMfaCancelled: "खाते का सत्यापन रद्द कर दिया गया।",
  errorMfaUnsupported: "इस खाते में कोई समर्थित ऑथेंटिकेटर ऐप नहीं है।",
  errorUnverifiedEmail: "एडमिन द्वारा स्वीकृत, सत्यापित ईमेल पते का उपयोग करें।",
  errorUnconfigured: "साइन इन सेटिंग मौजूद नहीं हैं। कृपया सहायता टीम से संपर्क करें।",
  errorServer: "WIFIGATE सर्वर से कनेक्ट नहीं हो पा रहा है। कृपया फिर से कोशिश करें।",
  errorSessionExpired: "आपके सेशन की समय-सीमा खत्म हो गई है। फिर से साइन इन करें।",
  errorForbidden: "ऐक्सेस की अनुमति नहीं है। सिस्टम एडमिन से संपर्क करें।",
  errorGeneric: "कुछ गड़बड़ हो गई। कृपया फिर से कोशिश करें।",
};
