// Sign-in page copy (/hr/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Prijava",
  heading: "Prijava na WIFIGATE",
  home: "Početna stranica WIFIGATE",
  google: "Nastavite s Googleom",
  apple: "Nastavite s Appleom",
  signingInLabel: "Prijava u tijeku",
  legal: "Nastavkom prihvaćate sljedeće: {terms} i {privacy}.",
  terms: "Uvjeti korištenja",
  privacy: "Pravila o privatnosti",
  chooseLanguage: "Odaberite jezik",
  close: "Zatvori",
  stagingTitle: "Lokalno testno okruženje",
  stagingText: "Koriste se simulirani Google ili Apple računi. Lozinka pružatelja nije potrebna.",
  mfaTitle: "Potvrda aplikacijom za autentifikaciju",
  mfaText: "Unesite trenutačni kôd iz aplikacije za autentifikaciju kako biste dovršili prijavu.",
  mfaFactor: "Aplikacija za autentifikaciju",
  mfaCode: "Kôd za potvrdu",
  mfaVerify: "Potvrdi",
  mfaCancel: "Odustani",
  mfaHelp: "Izgubili ste pristup? Obratite se administratoru platforme radi provjere identiteta i vraćanja metode autentifikacije.",
  authenticatorN: "Aplikacija za autentifikaciju {n}",
  verifying: "Provjera...",
  checking: "Provjeravamo vaš pristup...",
  opening: "Otvaramo nadzornu ploču...",
  signingIn: "Prijava...",
  humanReady: "Uspjeli ste. Sada nastavite s Googleom ili Appleom.",
  accessUnavailable: "Trenutačno nije moguće provjeriti pristup. Pokušajte ponovno.",
  gameTitle: "Nisam robot",
  gameInstruction: "Za potvrdu povucite automobil do otvorenih vrata",
  gameFooter: "Provjera čovjeka · WIFIGATE",
  gameKeyboard: "Automobil je u traci {lane} od 3. Strelice mijenjaju traku, Enter vozi.",
  gameGate: "Vrata {n}, {state}",
  gateOpen: "otvorena",
  gateClosed: "zatvorena",
  gameRetry: "Ne baš. Uđite u zelena vrata.",
  gameLocked: "Previše pokušaja. Pokušajte ponovno za {s} s.",
  gameDone: "Potvrđeno. Niste robot.",
  errorCancelled: "Prijava je otkazana.",
  errorPopupBlocked: "Preglednik je blokirao prozor za prijavu.",
  errorInvalidCode: "Kôd je netočan ili je istekao.",
  errorMissingCode: "Unesite kôd iz aplikacije za autentifikaciju.",
  errorNetwork: "Povezivanje nije moguće. Provjerite mrežnu vezu.",
  errorMfaCancelled: "Potvrda računa je otkazana.",
  errorMfaUnsupported: "Ovaj račun nema podržanu aplikaciju za autentifikaciju.",
  errorUnverifiedEmail: "Upotrijebite potvrđenu adresu e-pošte koju je odobrio administrator.",
  errorUnconfigured: "Nedostaju postavke prijave. Obratite se podršci.",
  errorServer: "Nije moguće povezati se s poslužiteljem WIFIGATE. Pokušajte ponovno.",
  errorSessionExpired: "Prijava je istekla. Ponovno se prijavite.",
  errorForbidden: "Pristup nije dopušten. Obratite se administratoru sustava.",
  errorGeneric: "Nešto nije u redu. Pokušajte ponovno.",
};
