// Sign-in page copy (/hu/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Bejelentkezés",
  heading: "Bejelentkezés a WIFIGATE-be",
  home: "WIFIGATE kezdőlap",
  google: "Folytatás a Google-lal",
  apple: "Folytatás az Apple-lel",
  signingInLabel: "Bejelentkezés folyamatban",
  legal: "A folytatással elfogadod a következőket: {terms} és {privacy}.",
  terms: "Felhasználási feltételek",
  privacy: "Adatvédelmi irányelvek",
  chooseLanguage: "Válassz nyelvet",
  close: "Bezárás",
  stagingTitle: "Helyi tesztkörnyezet",
  stagingText: "Szimulált Google- vagy Apple-fiókokat használsz. A szolgáltató jelszavára nincs szükség.",
  mfaTitle: "Ellenőrzés hitelesítő alkalmazással",
  mfaText: "A bejelentkezés befejezéséhez add meg a hitelesítő alkalmazásban látható aktuális kódot.",
  mfaFactor: "Hitelesítő alkalmazás",
  mfaCode: "Ellenőrző kód",
  mfaVerify: "Ellenőrzés",
  mfaCancel: "Mégse",
  mfaHelp: "Elvesztetted a hozzáférést? Fordulj a platform adminisztrátorához a személyazonosságod ellenőrzéséhez és a hitelesítési mód visszaállításához.",
  authenticatorN: "Hitelesítő alkalmazás {n}",
  verifying: "Ellenőrzés...",
  checking: "Hozzáférés ellenőrzése...",
  opening: "Irányítópult megnyitása...",
  signingIn: "Bejelentkezés...",
  humanReady: "Sikerült. Most folytasd a Google-lal vagy az Apple-lel.",
  accessUnavailable: "A hozzáférés most nem ellenőrizhető. Próbáld újra.",
  gameTitle: "Nem vagyok robot",
  gameInstruction: "A megerősítéshez húzd az autót a nyitott kapuba",
  gameFooter: "Emberi ellenőrzés · WIFIGATE",
  gameKeyboard: "Az autó a(z) {lane}. sávban van a 3-ból. A nyílbillentyűkkel sávot válthatsz, az Enter elindítja.",
  gameGate: "{n}. kapu, {state}",
  gateOpen: "nyitva",
  gateClosed: "zárva",
  gameRetry: "Majdnem. Hajts be a zöld kapuba.",
  gameLocked: "Túl sok próbálkozás. Próbáld újra {s} másodperc múlva.",
  gameDone: "Ellenőrizve. Nem vagy robot.",
  errorCancelled: "A bejelentkezés megszakadt.",
  errorPopupBlocked: "A böngésző letiltotta a bejelentkezési ablakot.",
  errorInvalidCode: "A kód hibás vagy lejárt.",
  errorMissingCode: "Add meg a hitelesítő alkalmazás kódját.",
  errorNetwork: "Nem sikerült csatlakozni. Ellenőrizd a hálózati kapcsolatot.",
  errorMfaCancelled: "A fiók ellenőrzése megszakadt.",
  errorMfaUnsupported: "Ehhez a fiókhoz nincs támogatott hitelesítő alkalmazás.",
  errorUnverifiedEmail: "Az adminisztrátor által jóváhagyott, ellenőrzött e-mail-címet használd.",
  errorUnconfigured: "Hiányoznak a bejelentkezési beállítások. Fordulj az ügyfélszolgálathoz.",
  errorServer: "Nem érhető el a WIFIGATE szervere. Próbáld újra.",
  errorSessionExpired: "A bejelentkezés lejárt. Jelentkezz be újra.",
  errorForbidden: "A hozzáférés nem engedélyezett. Fordulj a rendszergazdához.",
  errorGeneric: "Hiba történt. Próbáld újra.",
};
