// Sign-in page copy (/id/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Masuk",
  heading: "Masuk ke WIFIGATE",
  home: "Beranda WIFIGATE",
  google: "Lanjutkan dengan Google",
  apple: "Lanjutkan dengan Apple",
  signingInLabel: "Sedang masuk",
  legal: "Dengan melanjutkan, Anda menyetujui {terms} dan {privacy}.",
  terms: "Ketentuan",
  privacy: "Kebijakan Privasi",
  chooseLanguage: "Pilih bahasa",
  close: "Tutup",
  stagingTitle: "Lingkungan uji lokal",
  stagingText: "Menggunakan akun Google atau Apple tiruan. Tidak perlu kata sandi penyedia.",
  mfaTitle: "Verifikasi dengan aplikasi autentikator",
  mfaText: "Masukkan kode terbaru dari aplikasi autentikator untuk menyelesaikan proses masuk.",
  mfaFactor: "Aplikasi autentikator",
  mfaCode: "Kode verifikasi",
  mfaVerify: "Verifikasi",
  mfaCancel: "Batal",
  mfaHelp: "Kehilangan akses? Hubungi pengelola platform untuk memverifikasi identitas dan memulihkan metode autentikasi Anda.",
  authenticatorN: "Aplikasi autentikator {n}",
  verifying: "Memverifikasi...",
  checking: "Memeriksa akses Anda...",
  opening: "Membuka dasbor...",
  signingIn: "Sedang masuk...",
  humanReady: "Berhasil. Sekarang lanjutkan dengan Google atau Apple.",
  accessUnavailable: "Akses tidak dapat diperiksa saat ini. Silakan coba lagi.",
  gameTitle: "Saya bukan robot",
  gameInstruction: "Untuk mengonfirmasi, seret mobil ke gerbang yang terbuka",
  gameFooter: "Verifikasi manusia · WIFIGATE",
  gameKeyboard: "Mobil di lajur {lane} dari 3. Tombol panah mengganti lajur, Enter untuk melaju.",
  gameGate: "Gerbang {n}, {state}",
  gateOpen: "terbuka",
  gateClosed: "tertutup",
  gameRetry: "Belum tepat. Masuklah ke gerbang hijau.",
  gameLocked: "Terlalu banyak percobaan. Coba lagi dalam {s} detik.",
  gameDone: "Terverifikasi. Anda bukan robot.",
  errorCancelled: "Proses masuk dibatalkan.",
  errorPopupBlocked: "Peramban memblokir jendela masuk.",
  errorInvalidCode: "Kode salah atau sudah kedaluwarsa.",
  errorMissingCode: "Masukkan kode dari aplikasi autentikator.",
  errorNetwork: "Tidak dapat terhubung. Periksa koneksi jaringan Anda.",
  errorMfaCancelled: "Verifikasi akun dibatalkan.",
  errorMfaUnsupported: "Akun ini tidak memiliki aplikasi autentikator yang didukung.",
  errorUnverifiedEmail: "Gunakan email terverifikasi yang disetujui oleh pengelola.",
  errorUnconfigured: "Pengaturan masuk tidak lengkap. Hubungi dukungan.",
  errorServer: "Tidak dapat terhubung ke server WIFIGATE. Silakan coba lagi.",
  errorSessionExpired: "Sesi masuk telah berakhir. Silakan masuk lagi.",
  errorForbidden: "Akses tidak diizinkan. Hubungi pengelola sistem.",
  errorGeneric: "Terjadi kesalahan. Silakan coba lagi.",
};
