// Sign-in page copy (/it/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Accedi",
  heading: "Accedi a WIFIGATE",
  home: "Pagina iniziale di WIFIGATE",
  google: "Continua con Google",
  apple: "Continua con Apple",
  signingInLabel: "Accesso in corso",
  legal: "Continuando, accetti i {terms} e l'{privacy}.",
  terms: "Termini di utilizzo",
  privacy: "Informativa sulla privacy",
  chooseLanguage: "Scegli la lingua",
  close: "Chiudi",
  stagingTitle: "Ambiente di prova locale",
  stagingText: "Usa account Google o Apple simulati. Non serve la password del fornitore.",
  mfaTitle: "Verifica con l'app di autenticazione",
  mfaText: "Inserisci il codice attuale dell'app di autenticazione per completare l'accesso.",
  mfaFactor: "App di autenticazione",
  mfaCode: "Codice di verifica",
  mfaVerify: "Verifica",
  mfaCancel: "Annulla",
  mfaHelp: "Hai perso l'accesso? Contatta l'amministratore della piattaforma per verificare la tua identità e recuperare il metodo di autenticazione.",
  authenticatorN: "App di autenticazione {n}",
  verifying: "Verifica in corso...",
  checking: "Controllo del tuo accesso...",
  opening: "Apertura della dashboard...",
  signingIn: "Accesso in corso...",
  humanReady: "Superato. Ora puoi continuare con Google o Apple.",
  accessUnavailable: "Impossibile verificare l'accesso al momento. Riprova.",
  gameTitle: "Non sono un robot",
  gameInstruction: "Per confermare, trascina l'auto nel cancello aperto",
  gameFooter: "Verifica umana · WIFIGATE",
  gameKeyboard: "Auto nella corsia {lane} di 3. Le frecce cambiano corsia, Enter fa partire.",
  gameGate: "Cancello {n}, {state}",
  gateOpen: "aperto",
  gateClosed: "chiuso",
  gameRetry: "Non proprio. Entra nel cancello verde.",
  gameLocked: "Troppi tentativi. Riprova tra {s} secondi.",
  gameDone: "Verificato. Non sei un robot.",
  errorCancelled: "L'accesso è stato annullato.",
  errorPopupBlocked: "Il browser ha bloccato la finestra di accesso.",
  errorInvalidCode: "Il codice non è corretto o è scaduto.",
  errorMissingCode: "Inserisci il codice dell'app di autenticazione.",
  errorNetwork: "Impossibile connettersi. Controlla la connessione di rete.",
  errorMfaCancelled: "La verifica dell'account è stata annullata.",
  errorMfaUnsupported: "Questo account non ha un'app di autenticazione supportata.",
  errorUnverifiedEmail: "Usa l'indirizzo email verificato approvato dall'amministratore.",
  errorUnconfigured: "Mancano le impostazioni di accesso. Contatta l'assistenza.",
  errorServer: "Impossibile raggiungere il server WIFIGATE. Riprova.",
  errorSessionExpired: "La sessione è scaduta. Accedi di nuovo.",
  errorForbidden: "Accesso non autorizzato. Contatta l'amministratore di sistema.",
  errorGeneric: "Si è verificato un errore. Riprova.",
};
