// Sign-in page copy (/ja/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "ログイン",
  heading: "WIFIGATE にログイン",
  home: "WIFIGATE ホーム",
  google: "Google で続行",
  apple: "Apple で続ける",
  signingInLabel: "ログイン中",
  legal: "続行すると、{terms}と{privacy}に同意したことになります。",
  terms: "利用規約",
  privacy: "プライバシーポリシー",
  chooseLanguage: "言語を選択",
  close: "閉じる",
  stagingTitle: "ローカルテスト環境",
  stagingText: "模擬の Google または Apple アカウントを使用します。プロバイダーのパスワードは不要です。",
  mfaTitle: "認証アプリで確認",
  mfaText: "ログインを完了するには、認証アプリに表示されている現在のコードを入力してください。",
  mfaFactor: "認証アプリ",
  mfaCode: "確認コード",
  mfaVerify: "確認",
  mfaCancel: "キャンセル",
  mfaHelp: "アクセスできなくなった場合は、プラットフォーム管理者に連絡して本人確認と認証方法の復元を依頼してください。",
  authenticatorN: "認証アプリ {n}",
  verifying: "確認しています...",
  checking: "アクセス権を確認しています...",
  opening: "ダッシュボードを開いています...",
  signingIn: "ログインしています...",
  humanReady: "確認が完了しました。Google または Apple で続行してください。",
  accessUnavailable: "現在アクセスを確認できません。もう一度お試しください。",
  gameTitle: "私はロボットではありません",
  gameInstruction: "確認するには、車を開いているゲートまでドラッグしてください",
  gameFooter: "人間確認 · WIFIGATE",
  gameKeyboard: "車は3車線中の{lane}番目の車線にいます。矢印キーで車線を変更し、Enter で進みます。",
  gameGate: "ゲート {n}、{state}",
  gateOpen: "開いています",
  gateClosed: "閉じています",
  gameRetry: "もう少しです。緑のゲートに入ってください。",
  gameLocked: "試行回数が多すぎます。{s} 秒後にもう一度お試しください。",
  gameDone: "確認しました。あなたはロボットではありません。",
  errorCancelled: "ログインがキャンセルされました。",
  errorPopupBlocked: "ブラウザがログインウィンドウをブロックしました。",
  errorInvalidCode: "コードが正しくないか、有効期限が切れています。",
  errorMissingCode: "認証アプリのコードを入力してください。",
  errorNetwork: "接続できません。ネットワーク接続を確認してください。",
  errorMfaCancelled: "アカウントの確認がキャンセルされました。",
  errorMfaUnsupported: "このアカウントには対応する認証アプリがありません。",
  errorUnverifiedEmail: "管理者が承認した確認済みのメールアドレスを使用してください。",
  errorUnconfigured: "ログイン設定がありません。サポートにお問い合わせください。",
  errorServer: "WIFIGATE サーバーに接続できません。もう一度お試しください。",
  errorSessionExpired: "ログインの有効期限が切れました。もう一度ログインしてください。",
  errorForbidden: "アクセスが許可されていません。システム管理者にお問い合わせください。",
  errorGeneric: "問題が発生しました。もう一度お試しください。",
};
