// Sign-in page copy (/ko/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "로그인",
  heading: "WIFIGATE에 로그인",
  home: "WIFIGATE 홈",
  google: "Google로 계속하기",
  apple: "Apple로 계속하기",
  signingInLabel: "로그인 중",
  legal: "계속하면 {terms} 및 {privacy}에 동의하는 것으로 간주됩니다.",
  terms: "이용약관",
  privacy: "개인정보처리방침",
  chooseLanguage: "언어 선택",
  close: "닫기",
  stagingTitle: "로컬 테스트 환경",
  stagingText: "모의 Google 또는 Apple 계정을 사용합니다. 제공업체 비밀번호는 필요하지 않습니다.",
  mfaTitle: "인증 앱으로 인증",
  mfaText: "로그인을 완료하려면 인증 앱에 표시된 현재 코드를 입력하세요.",
  mfaFactor: "인증 앱",
  mfaCode: "인증 코드",
  mfaVerify: "인증",
  mfaCancel: "취소",
  mfaHelp: "액세스할 수 없나요? 플랫폼 관리자에게 문의하여 본인 확인 후 인증 수단을 복구하세요.",
  authenticatorN: "인증 앱 {n}",
  verifying: "인증 중...",
  checking: "액세스 권한 확인 중...",
  opening: "대시보드 여는 중...",
  signingIn: "로그인 중...",
  humanReady: "통과했습니다. 이제 Google 또는 Apple로 계속하세요.",
  accessUnavailable: "지금은 액세스를 확인할 수 없습니다. 다시 시도하세요.",
  gameTitle: "로봇이 아닙니다.",
  gameInstruction: "확인하려면 자동차를 열린 게이트로 드래그하세요",
  gameFooter: "사람 확인 · WIFIGATE",
  gameKeyboard: "자동차가 3개 차로 중 {lane}번 차로에 있습니다. 화살표 키로 차로를 바꾸고 Enter 키로 주행합니다.",
  gameGate: "게이트 {n}, {state}",
  gateOpen: "열림",
  gateClosed: "닫힘",
  gameRetry: "조금 빗나갔습니다. 초록색 게이트로 들어가세요.",
  gameLocked: "시도 횟수가 너무 많습니다. {s}초 후에 다시 시도하세요.",
  gameDone: "인증되었습니다. 로봇이 아닙니다.",
  errorCancelled: "로그인이 취소되었습니다.",
  errorPopupBlocked: "브라우저에서 로그인 창을 차단했습니다.",
  errorInvalidCode: "코드가 올바르지 않거나 만료되었습니다.",
  errorMissingCode: "인증 앱의 코드를 입력하세요.",
  errorNetwork: "연결할 수 없습니다. 네트워크 연결을 확인하세요.",
  errorMfaCancelled: "계정 인증이 취소되었습니다.",
  errorMfaUnsupported: "이 계정에는 지원되는 인증 앱이 없습니다.",
  errorUnverifiedEmail: "관리자가 승인한 인증된 이메일을 사용하세요.",
  errorUnconfigured: "로그인 설정이 없습니다. 고객지원에 문의하세요.",
  errorServer: "WIFIGATE 서버에 연결할 수 없습니다. 다시 시도하세요.",
  errorSessionExpired: "로그인이 만료되었습니다. 다시 로그인하세요.",
  errorForbidden: "액세스가 허용되지 않습니다. 시스템 관리자에게 문의하세요.",
  errorGeneric: "문제가 발생했습니다. 다시 시도하세요.",
};
