// Sign-in page copy (/mr/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "साइन इन",
  heading: "WIFIGATE मध्ये साइन इन करा",
  home: "WIFIGATE मुख्यपृष्ठ",
  google: "Google सह सुरू ठेवा",
  apple: "Apple सह सुरू ठेवा",
  signingInLabel: "साइन इन होत आहे",
  legal: "पुढे सुरू ठेवून, तुम्ही {terms} आणि {privacy} यांना सहमती देता.",
  terms: "अटी",
  privacy: "गोपनीयता धोरण",
  chooseLanguage: "भाषा निवडा",
  close: "बंद करा",
  stagingTitle: "स्थानिक चाचणी वातावरण",
  stagingText: "बनावट Google किंवा Apple खाती वापरली जातात. पुरवठादाराच्या पासवर्डची आवश्यकता नाही.",
  mfaTitle: "ऑथेंटिकेटर अ‍ॅपद्वारे पडताळणी",
  mfaText: "साइन इन पूर्ण करण्यासाठी तुमच्या ऑथेंटिकेटर अ‍ॅपमधील सध्याचा कोड एंटर करा.",
  mfaFactor: "ऑथेंटिकेटर अ‍ॅप",
  mfaCode: "पडताळणी कोड",
  mfaVerify: "पडताळा",
  mfaCancel: "रद्द करा",
  mfaHelp: "ॲक्सेस गमावला? ओळख पडताळण्यासाठी आणि पडताळणीची पद्धत परत मिळवण्यासाठी प्लॅटफॉर्म ॲडमिनशी संपर्क साधा.",
  authenticatorN: "ऑथेंटिकेटर अ‍ॅप {n}",
  verifying: "पडताळणी होत आहे...",
  checking: "तुमचा ॲक्सेस तपासत आहोत...",
  opening: "डॅशबोर्ड उघडत आहोत...",
  signingIn: "साइन इन होत आहे...",
  humanReady: "तुम्ही उत्तीर्ण झालात. आता Google किंवा Apple सह सुरू ठेवा.",
  accessUnavailable: "सध्या ॲक्सेस तपासता येत नाही. कृपया पुन्हा प्रयत्न करा.",
  gameTitle: "मी रोबोट नाही",
  gameInstruction: "पुष्टी करण्यासाठी, कार उघड्या गेटपर्यंत ओढा",
  gameFooter: "मानवी पडताळणी · WIFIGATE",
  gameKeyboard: "कार 3 पैकी लेन {lane} मध्ये आहे. बाण कळांनी लेन बदलते, Enter ने कार पुढे जाते.",
  gameGate: "गेट {n}, {state}",
  gateOpen: "उघडे",
  gateClosed: "बंद",
  gameRetry: "थोडक्यात चुकले. हिरव्या गेटमध्ये जा.",
  gameLocked: "खूप जास्त प्रयत्न झाले. {s} सेकंदांनंतर पुन्हा प्रयत्न करा.",
  gameDone: "पडताळणी झाली. तुम्ही रोबोट नाही.",
  errorCancelled: "साइन इन रद्द केले.",
  errorPopupBlocked: "ब्राउझरने साइन इन विंडो ब्लॉक केली.",
  errorInvalidCode: "कोड चुकीचा आहे किंवा त्याची मुदत संपली आहे.",
  errorMissingCode: "तुमच्या ऑथेंटिकेटर अ‍ॅपमधील कोड एंटर करा.",
  errorNetwork: "कनेक्ट करता येत नाही. तुमचे नेटवर्क कनेक्शन तपासा.",
  errorMfaCancelled: "खात्याची पडताळणी रद्द केली.",
  errorMfaUnsupported: "या खात्यामध्ये समर्थित ऑथेंटिकेटर अ‍ॅप नाही.",
  errorUnverifiedEmail: "ॲडमिनने मंजूर केलेला पडताळलेला ईमेल पत्ता वापरा.",
  errorUnconfigured: "साइन इन सेटिंग्ज उपलब्ध नाहीत. कृपया सपोर्टशी संपर्क साधा.",
  errorServer: "WIFIGATE सर्व्हरशी कनेक्ट करता येत नाही. कृपया पुन्हा प्रयत्न करा.",
  errorSessionExpired: "सत्राची मुदत संपली आहे. पुन्हा साइन इन करा.",
  errorForbidden: "ॲक्सेसची परवानगी नाही. सिस्टम ॲडमिनशी संपर्क साधा.",
  errorGeneric: "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.",
};
