// Sign-in page copy (/ms/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Log masuk",
  heading: "Log masuk ke WIFIGATE",
  home: "Laman utama WIFIGATE",
  google: "Teruskan dengan Google",
  apple: "Teruskan dengan Apple",
  signingInLabel: "Sedang log masuk",
  legal: "Dengan meneruskan, anda bersetuju dengan {terms} dan {privacy}.",
  terms: "Terma",
  privacy: "Dasar Privasi",
  chooseLanguage: "Pilih bahasa",
  close: "Tutup",
  stagingTitle: "Persekitaran ujian setempat",
  stagingText: "Akaun Google atau Apple olok-olok digunakan. Kata laluan pembekal tidak diperlukan.",
  mfaTitle: "Pengesahan dengan apl pengesah",
  mfaText: "Masukkan kod semasa daripada apl pengesah untuk melengkapkan log masuk.",
  mfaFactor: "Apl pengesah",
  mfaCode: "Kod pengesahan",
  mfaVerify: "Sahkan",
  mfaCancel: "Batal",
  mfaHelp: "Hilang akses? Hubungi pentadbir platform untuk mengesahkan identiti dan memulihkan kaedah pengesahan anda.",
  authenticatorN: "Apl pengesah {n}",
  verifying: "Mengesahkan...",
  checking: "Menyemak akses anda...",
  opening: "Membuka papan pemuka...",
  signingIn: "Sedang log masuk...",
  humanReady: "Berjaya. Sekarang teruskan dengan Google atau Apple.",
  accessUnavailable: "Akses tidak dapat disemak sekarang. Sila cuba lagi.",
  gameTitle: "Saya bukan robot",
  gameInstruction: "Untuk mengesahkan, seret kereta ke pintu pagar yang terbuka",
  gameFooter: "Semakan manusia · WIFIGATE",
  gameKeyboard: "Kereta di lorong {lane} daripada 3. Kekunci anak panah menukar lorong, Enter untuk memandu.",
  gameGate: "Pintu pagar {n}, {state}",
  gateOpen: "terbuka",
  gateClosed: "tertutup",
  gameRetry: "Hampir. Pandu masuk ke pintu pagar hijau.",
  gameLocked: "Terlalu banyak cubaan. Cuba lagi dalam {s} saat.",
  gameDone: "Disahkan. Anda bukan robot.",
  errorCancelled: "Log masuk dibatalkan.",
  errorPopupBlocked: "Pelayar menyekat tetingkap log masuk.",
  errorInvalidCode: "Kod tidak betul atau telah tamat tempoh.",
  errorMissingCode: "Masukkan kod daripada apl pengesah.",
  errorNetwork: "Tidak dapat menyambung. Semak sambungan rangkaian anda.",
  errorMfaCancelled: "Pengesahan akaun dibatalkan.",
  errorMfaUnsupported: "Akaun ini tiada apl pengesah yang disokong.",
  errorUnverifiedEmail: "Gunakan e-mel disahkan yang diluluskan oleh pentadbir.",
  errorUnconfigured: "Tetapan log masuk tiada. Hubungi sokongan.",
  errorServer: "Tidak dapat menghubungi pelayan WIFIGATE. Sila cuba lagi.",
  errorSessionExpired: "Sesi log masuk telah tamat. Log masuk semula.",
  errorForbidden: "Akses tidak dibenarkan. Hubungi pentadbir sistem.",
  errorGeneric: "Ada sesuatu yang tidak kena. Sila cuba lagi.",
};
