// Sign-in page copy (/nl/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Inloggen",
  heading: "Inloggen bij WIFIGATE",
  home: "Startpagina van WIFIGATE",
  google: "Doorgaan met Google",
  apple: "Doorgaan met Apple",
  signingInLabel: "Bezig met inloggen",
  legal: "Door verder te gaan, ga je akkoord met de {terms} en het {privacy}.",
  terms: "Gebruiksvoorwaarden",
  privacy: "Privacybeleid",
  chooseLanguage: "Kies een taal",
  close: "Sluiten",
  stagingTitle: "Lokale testomgeving",
  stagingText: "Gebruik gesimuleerde Google- of Apple-accounts. Een wachtwoord van de provider is niet nodig.",
  mfaTitle: "Verificatie met je authenticatie-app",
  mfaText: "Voer de huidige code uit je authenticatie-app in om het inloggen te voltooien.",
  mfaFactor: "Authenticatie-app",
  mfaCode: "Verificatiecode",
  mfaVerify: "Verifiëren",
  mfaCancel: "Annuleren",
  mfaHelp: "Geen toegang meer? Neem contact op met de platformbeheerder om je identiteit te verifiëren en je verificatiemethode te herstellen.",
  authenticatorN: "Authenticatie-app {n}",
  verifying: "Bezig met verifiëren...",
  checking: "Je toegang wordt gecontroleerd...",
  opening: "Dashboard wordt geopend...",
  signingIn: "Bezig met inloggen...",
  humanReady: "Gelukt. Je kunt nu doorgaan met Google of Apple.",
  accessUnavailable: "De toegang kan nu niet worden gecontroleerd. Probeer het opnieuw.",
  gameTitle: "Ik ben geen robot",
  gameInstruction: "Sleep de auto naar de open poort om te bevestigen",
  gameFooter: "Menselijke controle · WIFIGATE",
  gameKeyboard: "Auto op rijstrook {lane} van 3. Pijltjestoetsen wisselen van rijstrook, Enter rijdt.",
  gameGate: "Poort {n}, {state}",
  gateOpen: "geopend",
  gateClosed: "gesloten",
  gameRetry: "Bijna. Rijd de groene poort in.",
  gameLocked: "Te veel pogingen. Probeer het over {s} seconden opnieuw.",
  gameDone: "Geverifieerd. Je bent geen robot.",
  errorCancelled: "Het inloggen is geannuleerd.",
  errorPopupBlocked: "Je browser heeft het inlogvenster geblokkeerd.",
  errorInvalidCode: "De code is onjuist of verlopen.",
  errorMissingCode: "Voer de code uit je authenticatie-app in.",
  errorNetwork: "Kan geen verbinding maken. Controleer je netwerkverbinding.",
  errorMfaCancelled: "De accountverificatie is geannuleerd.",
  errorMfaUnsupported: "Dit account heeft geen ondersteunde authenticatie-app.",
  errorUnverifiedEmail: "Gebruik het geverifieerde e-mailadres dat door de beheerder is goedgekeurd.",
  errorUnconfigured: "De inloginstellingen ontbreken. Neem contact op met de klantenservice.",
  errorServer: "Kan de WIFIGATE-server niet bereiken. Probeer het opnieuw.",
  errorSessionExpired: "Je sessie is verlopen. Log opnieuw in.",
  errorForbidden: "Toegang niet toegestaan. Neem contact op met de systeembeheerder.",
  errorGeneric: "Er is iets misgegaan. Probeer het opnieuw.",
};
