// Sign-in page copy (/no/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Logg inn",
  heading: "Logg inn på WIFIGATE",
  home: "WIFIGATE-forsiden",
  google: "Fortsett med Google",
  apple: "Fortsett med Apple",
  signingInLabel: "Logger inn",
  legal: "Ved å fortsette godtar du {terms} og {privacy}.",
  terms: "vilkårene",
  privacy: "personvernerklæringen",
  chooseLanguage: "Velg språk",
  close: "Lukk",
  stagingTitle: "Lokalt testmiljø",
  stagingText: "Bruk simulerte Google- eller Apple-kontoer. Du trenger ikke passordet til leverandøren.",
  mfaTitle: "Bekreftelse med autentiseringsappen",
  mfaText: "Skriv inn den gjeldende koden fra autentiseringsappen for å fullføre innloggingen.",
  mfaFactor: "Autentiseringsapp",
  mfaCode: "Bekreftelseskode",
  mfaVerify: "Bekreft",
  mfaCancel: "Avbryt",
  mfaHelp: "Mistet tilgangen? Kontakt plattformadministratoren for å bekrefte identiteten din og gjenopprette autentiseringsmetoden.",
  authenticatorN: "Autentiseringsapp {n}",
  verifying: "Bekrefter...",
  checking: "Sjekker tilgangen din...",
  opening: "Åpner kontrollpanelet...",
  signingIn: "Logger inn...",
  humanReady: "Bestått. Nå kan du fortsette med Google eller Apple.",
  accessUnavailable: "Kan ikke sjekke tilgangen akkurat nå. Prøv igjen.",
  gameTitle: "Jeg er ikke en robot",
  gameInstruction: "Dra bilen inn i den åpne porten for å bekrefte",
  gameFooter: "Menneskesjekk · WIFIGATE",
  gameKeyboard: "Bilen er i felt {lane} av 3. Piltastene bytter felt, Enter kjører.",
  gameGate: "Port {n}, {state}",
  gateOpen: "åpen",
  gateClosed: "lukket",
  gameRetry: "Ikke helt. Kjør inn i den grønne porten.",
  gameLocked: "For mange forsøk. Prøv igjen om {s} sekunder.",
  gameDone: "Bekreftet. Du er ikke en robot.",
  errorCancelled: "Innloggingen ble avbrutt.",
  errorPopupBlocked: "Nettleseren blokkerte innloggingsvinduet.",
  errorInvalidCode: "Koden er feil eller utløpt.",
  errorMissingCode: "Skriv inn koden fra autentiseringsappen.",
  errorNetwork: "Kan ikke koble til. Sjekk nettverkstilkoblingen.",
  errorMfaCancelled: "Kontobekreftelsen ble avbrutt.",
  errorMfaUnsupported: "Denne kontoen har ingen støttet autentiseringsapp.",
  errorUnverifiedEmail: "Bruk den bekreftede e-postadressen som administratoren har godkjent.",
  errorUnconfigured: "Innloggingsinnstillingene mangler. Kontakt kundestøtte.",
  errorServer: "Kan ikke nå WIFIGATE-serveren. Prøv igjen.",
  errorSessionExpired: "Økten er utløpt. Logg inn på nytt.",
  errorForbidden: "Tilgang er ikke tillatt. Kontakt systemadministratoren.",
  errorGeneric: "Noe gikk galt. Prøv igjen.",
};
