// Sign-in page copy (/pl/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Logowanie",
  heading: "Zaloguj się do WIFIGATE",
  home: "Strona główna WIFIGATE",
  google: "Kontynuuj z Google",
  apple: "Kontynuuj z Apple",
  signingInLabel: "Logowanie",
  legal: "Kontynuując, akceptujesz dokumenty: {terms} oraz {privacy}.",
  terms: "Warunki korzystania",
  privacy: "Polityka prywatności",
  chooseLanguage: "Wybierz język",
  close: "Zamknij",
  stagingTitle: "Lokalne środowisko testowe",
  stagingText: "Używasz symulowanych kont Google lub Apple. Hasło dostawcy nie jest potrzebne.",
  mfaTitle: "Weryfikacja w aplikacji uwierzytelniającej",
  mfaText: "Wpisz aktualny kod z aplikacji uwierzytelniającej, aby dokończyć logowanie.",
  mfaFactor: "Aplikacja uwierzytelniająca",
  mfaCode: "Kod weryfikacyjny",
  mfaVerify: "Zweryfikuj",
  mfaCancel: "Anuluj",
  mfaHelp: "Utracono dostęp? Skontaktuj się z administratorem platformy, aby potwierdzić tożsamość i odzyskać metodę uwierzytelniania.",
  authenticatorN: "Aplikacja uwierzytelniająca {n}",
  verifying: "Weryfikowanie...",
  checking: "Sprawdzanie dostępu...",
  opening: "Otwieranie panelu...",
  signingIn: "Logowanie...",
  humanReady: "Zaliczone. Teraz możesz kontynuować z Google lub Apple.",
  accessUnavailable: "Nie można teraz sprawdzić dostępu. Spróbuj ponownie.",
  gameTitle: "Nie jestem robotem",
  gameInstruction: "Aby potwierdzić, przeciągnij samochód do otwartej bramy",
  gameFooter: "Weryfikacja człowieka · WIFIGATE",
  gameKeyboard: "Samochód na pasie {lane} z 3. Strzałki zmieniają pas, Enter rusza.",
  gameGate: "Brama {n}, {state}",
  gateOpen: "otwarta",
  gateClosed: "zamknięta",
  gameRetry: "Prawie. Wjedź w zieloną bramę.",
  gameLocked: "Zbyt wiele prób. Spróbuj ponownie za {s} s.",
  gameDone: "Zweryfikowano. Nie jesteś robotem.",
  errorCancelled: "Logowanie zostało anulowane.",
  errorPopupBlocked: "Przeglądarka zablokowała okno logowania.",
  errorInvalidCode: "Kod jest nieprawidłowy lub wygasł.",
  errorMissingCode: "Wpisz kod z aplikacji uwierzytelniającej.",
  errorNetwork: "Nie można nawiązać połączenia. Sprawdź połączenie z siecią.",
  errorMfaCancelled: "Weryfikacja konta została anulowana.",
  errorMfaUnsupported: "To konto nie ma obsługiwanej aplikacji uwierzytelniającej.",
  errorUnverifiedEmail: "Użyj zweryfikowanego adresu e-mail zatwierdzonego przez administratora.",
  errorUnconfigured: "Brak ustawień logowania. Skontaktuj się z pomocą techniczną.",
  errorServer: "Nie można połączyć się z serwerem WIFIGATE. Spróbuj ponownie.",
  errorSessionExpired: "Sesja wygasła. Zaloguj się ponownie.",
  errorForbidden: "Brak uprawnień dostępu. Skontaktuj się z administratorem systemu.",
  errorGeneric: "Coś poszło nie tak. Spróbuj ponownie.",
};
