// Sign-in page copy (/pt/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Entrar",
  heading: "Entrar no WIFIGATE",
  home: "Página inicial do WIFIGATE",
  google: "Continuar com o Google",
  apple: "Continuar com a Apple",
  signingInLabel: "Entrando",
  legal: "Ao continuar, você concorda com os {terms} e com a {privacy}.",
  terms: "Termos de uso",
  privacy: "Política de privacidade",
  chooseLanguage: "Escolha o idioma",
  close: "Fechar",
  stagingTitle: "Ambiente de teste local",
  stagingText: "Use contas simuladas do Google ou da Apple. Não é necessária a senha do provedor.",
  mfaTitle: "Verificação pelo app autenticador",
  mfaText: "Digite o código atual do seu app autenticador para concluir o acesso.",
  mfaFactor: "App autenticador",
  mfaCode: "Código de verificação",
  mfaVerify: "Verificar",
  mfaCancel: "Cancelar",
  mfaHelp: "Perdeu o acesso? Entre em contato com o administrador da plataforma para verificar sua identidade e recuperar seu método de autenticação.",
  authenticatorN: "App autenticador {n}",
  verifying: "Verificando...",
  checking: "Verificando seu acesso...",
  opening: "Abrindo o painel...",
  signingIn: "Entrando...",
  humanReady: "Aprovado. Agora você pode continuar com o Google ou a Apple.",
  accessUnavailable: "Não é possível verificar o acesso agora. Tente novamente.",
  gameTitle: "Não sou um robô",
  gameInstruction: "Para confirmar, arraste o carro até o portão aberto",
  gameFooter: "Verificação humana · WIFIGATE",
  gameKeyboard: "Carro na faixa {lane} de 3. As setas trocam de faixa, Enter avança.",
  gameGate: "Portão {n}, {state}",
  gateOpen: "aberto",
  gateClosed: "fechado",
  gameRetry: "Quase. Entre pelo portão verde.",
  gameLocked: "Muitas tentativas. Tente novamente em {s} segundos.",
  gameDone: "Verificado. Você não é um robô.",
  errorCancelled: "O acesso foi cancelado.",
  errorPopupBlocked: "O navegador bloqueou a janela de acesso.",
  errorInvalidCode: "O código está incorreto ou expirou.",
  errorMissingCode: "Digite o código do seu app autenticador.",
  errorNetwork: "Não foi possível conectar. Verifique sua conexão de rede.",
  errorMfaCancelled: "A verificação da conta foi cancelada.",
  errorMfaUnsupported: "Esta conta não tem um app autenticador compatível.",
  errorUnverifiedEmail: "Use o e-mail verificado aprovado pelo administrador.",
  errorUnconfigured: "As configurações de acesso estão ausentes. Entre em contato com o suporte.",
  errorServer: "Não foi possível acessar o servidor do WIFIGATE. Tente novamente.",
  errorSessionExpired: "Sua sessão expirou. Entre novamente.",
  errorForbidden: "Acesso não autorizado. Entre em contato com o administrador do sistema.",
  errorGeneric: "Algo deu errado. Tente novamente.",
};
