// Sign-in page copy (/ro/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Conectare",
  heading: "Conectați-vă la WIFIGATE",
  home: "Pagina principală WIFIGATE",
  google: "Continuați cu Google",
  apple: "Continuați cu Apple",
  signingInLabel: "Se realizează conectarea",
  legal: "Dacă continuați, acceptați următoarele: {terms} și {privacy}.",
  terms: "Termeni și condiții",
  privacy: "Politica de confidențialitate",
  chooseLanguage: "Alegeți limba",
  close: "Închideți",
  stagingTitle: "Mediu de testare local",
  stagingText: "Se folosesc conturi Google sau Apple simulate. Nu este necesară parola furnizorului.",
  mfaTitle: "Verificare cu aplicația de autentificare",
  mfaText: "Introduceți codul curent din aplicația de autentificare pentru a finaliza conectarea.",
  mfaFactor: "Aplicație de autentificare",
  mfaCode: "Cod de verificare",
  mfaVerify: "Verificați",
  mfaCancel: "Anulați",
  mfaHelp: "Ați pierdut accesul? Contactați administratorul platformei pentru verificarea identității și recuperarea metodei de autentificare.",
  authenticatorN: "Aplicație de autentificare {n}",
  verifying: "Se verifică...",
  checking: "Se verifică accesul...",
  opening: "Se deschide panoul de control...",
  signingIn: "Se realizează conectarea...",
  humanReady: "Ați trecut verificarea. Acum continuați cu Google sau Apple.",
  accessUnavailable: "Accesul nu poate fi verificat acum. Încercați din nou.",
  gameTitle: "Nu sunt robot",
  gameInstruction: "Pentru confirmare, trageți mașina în poarta deschisă",
  gameFooter: "Verificare umană · WIFIGATE",
  gameKeyboard: "Mașina este pe banda {lane} din 3. Săgețile schimbă banda, Enter pornește.",
  gameGate: "Poarta {n}, {state}",
  gateOpen: "deschisă",
  gateClosed: "închisă",
  gameRetry: "Nu chiar. Intrați în poarta verde.",
  gameLocked: "Prea multe încercări. Încercați din nou peste {s} secunde.",
  gameDone: "Verificat. Nu sunteți robot.",
  errorCancelled: "Conectarea a fost anulată.",
  errorPopupBlocked: "Navigatorul web a blocat fereastra de conectare.",
  errorInvalidCode: "Codul este incorect sau a expirat.",
  errorMissingCode: "Introduceți codul din aplicația de autentificare.",
  errorNetwork: "Nu se poate realiza conexiunea. Verificați conexiunea la rețea.",
  errorMfaCancelled: "Verificarea contului a fost anulată.",
  errorMfaUnsupported: "Acest cont nu are o aplicație de autentificare acceptată.",
  errorUnverifiedEmail: "Folosiți adresa de e-mail verificată, aprobată de administrator.",
  errorUnconfigured: "Setările de conectare lipsesc. Contactați asistența.",
  errorServer: "Serverul WIFIGATE nu poate fi accesat. Încercați din nou.",
  errorSessionExpired: "Conectarea a expirat. Conectați-vă din nou.",
  errorForbidden: "Accesul nu este permis. Contactați administratorul de sistem.",
  errorGeneric: "A apărut o problemă. Încercați din nou.",
};
