// Sign-in page copy (/sk/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Prihlásenie",
  heading: "Prihlásenie do WIFIGATE",
  home: "Domovská stránka WIFIGATE",
  google: "Pokračovať cez Google",
  apple: "Pokračovať cez Apple",
  signingInLabel: "Prihlasovanie",
  legal: "Pokračovaním súhlasíte s dokumentmi {terms} a {privacy}.",
  terms: "Podmienky používania",
  privacy: "Zásady ochrany súkromia",
  chooseLanguage: "Vyberte jazyk",
  close: "Zavrieť",
  stagingTitle: "Lokálne testovacie prostredie",
  stagingText: "Používajú sa simulované účty Google alebo Apple. Heslo poskytovateľa nie je potrebné.",
  mfaTitle: "Overenie pomocou overovacej aplikácie",
  mfaText: "Zadajte aktuálny kód z overovacej aplikácie a dokončite prihlásenie.",
  mfaFactor: "Overovacia aplikácia",
  mfaCode: "Overovací kód",
  mfaVerify: "Overiť",
  mfaCancel: "Zrušiť",
  mfaHelp: "Stratili ste prístup? Obráťte sa na správcu platformy, ktorý overí vašu totožnosť a obnoví spôsob overenia.",
  authenticatorN: "Overovacia aplikácia {n}",
  verifying: "Overuje sa...",
  checking: "Kontrolujeme váš prístup...",
  opening: "Otvárame ovládací panel...",
  signingIn: "Prihlasuje sa...",
  humanReady: "Hotovo. Teraz pokračujte cez Google alebo Apple.",
  accessUnavailable: "Prístup momentálne nie je možné overiť. Skúste to znova.",
  gameTitle: "Nie som robot",
  gameInstruction: "Na potvrdenie presuňte auto do otvorenej brány",
  gameFooter: "Overenie človeka · WIFIGATE",
  gameKeyboard: "Auto je v pruhu {lane} z 3. Šípky menia pruh, Enter spustí jazdu.",
  gameGate: "Brána {n}, {state}",
  gateOpen: "otvorená",
  gateClosed: "zatvorená",
  gameRetry: "Takmer. Vojdite do zelenej brány.",
  gameLocked: "Príliš veľa pokusov. Skúste to znova o {s} s.",
  gameDone: "Overené. Nie ste robot.",
  errorCancelled: "Prihlásenie bolo zrušené.",
  errorPopupBlocked: "Prehliadač zablokoval prihlasovacie okno.",
  errorInvalidCode: "Kód je nesprávny alebo mu vypršala platnosť.",
  errorMissingCode: "Zadajte kód z overovacej aplikácie.",
  errorNetwork: "Nedá sa pripojiť. Skontrolujte pripojenie k sieti.",
  errorMfaCancelled: "Overenie účtu bolo zrušené.",
  errorMfaUnsupported: "Tento účet nemá podporovanú overovaciu aplikáciu.",
  errorUnverifiedEmail: "Použite overený e-mail schválený správcom.",
  errorUnconfigured: "Chýbajú nastavenia prihlásenia. Obráťte sa na podporu.",
  errorServer: "Nedá sa spojiť so serverom WIFIGATE. Skúste to znova.",
  errorSessionExpired: "Platnosť prihlásenia vypršala. Prihláste sa znova.",
  errorForbidden: "Prístup nie je povolený. Obráťte sa na správcu systému.",
  errorGeneric: "Niečo sa pokazilo. Skúste to znova.",
};
