// Sign-in page copy (/sl/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Prijava",
  heading: "Prijava v WIFIGATE",
  home: "Domača stran WIFIGATE",
  google: "Nadaljuj z računom Google",
  apple: "Nadaljuj z računom Apple",
  signingInLabel: "Prijavljanje",
  legal: "Z nadaljevanjem se strinjate z dokumentoma {terms} in {privacy}.",
  terms: "Pogoji uporabe",
  privacy: "Pravilnik o zasebnosti",
  chooseLanguage: "Izberite jezik",
  close: "Zapri",
  stagingTitle: "Lokalno preskusno okolje",
  stagingText: "Uporabljajo se simulirani računi Google ali Apple. Geslo ponudnika ni potrebno.",
  mfaTitle: "Preverjanje z aplikacijo za preverjanje pristnosti",
  mfaText: "Vnesite trenutno kodo iz aplikacije za preverjanje pristnosti, da dokončate prijavo.",
  mfaFactor: "Aplikacija za preverjanje pristnosti",
  mfaCode: "Koda za preverjanje",
  mfaVerify: "Preveri",
  mfaCancel: "Prekliči",
  mfaHelp: "Ste izgubili dostop? Obrnite se na skrbnika platforme, ki bo preveril vašo identiteto in obnovil način preverjanja.",
  authenticatorN: "Aplikacija za preverjanje pristnosti {n}",
  verifying: "Preverjanje...",
  checking: "Preverjamo vaš dostop...",
  opening: "Odpiramo nadzorno ploščo...",
  signingIn: "Prijavljanje...",
  humanReady: "Uspelo je. Zdaj nadaljujte z računom Google ali Apple.",
  accessUnavailable: "Dostopa trenutno ni mogoče preveriti. Poskusite znova.",
  gameTitle: "Nisem robot",
  gameInstruction: "Za potrditev povlecite avto v odprta vrata",
  gameFooter: "Preverjanje človeka · WIFIGATE",
  gameKeyboard: "Avto je na pasu {lane} od 3. Puščice zamenjajo pas, Enter požene vožnjo.",
  gameGate: "Vrata {n}, {state}",
  gateOpen: "odprta",
  gateClosed: "zaprta",
  gameRetry: "Ne čisto. Zapeljite v zelena vrata.",
  gameLocked: "Preveč poskusov. Poskusite znova čez {s} s.",
  gameDone: "Preverjeno. Niste robot.",
  errorCancelled: "Prijava je bila preklicana.",
  errorPopupBlocked: "Brskalnik je blokiral okno za prijavo.",
  errorInvalidCode: "Koda je napačna ali je potekla.",
  errorMissingCode: "Vnesite kodo iz aplikacije za preverjanje pristnosti.",
  errorNetwork: "Povezava ni mogoča. Preverite omrežno povezavo.",
  errorMfaCancelled: "Preverjanje računa je bilo preklicano.",
  errorMfaUnsupported: "Ta račun nima podprte aplikacije za preverjanje pristnosti.",
  errorUnverifiedEmail: "Uporabite preverjeni e-poštni naslov, ki ga je odobril skrbnik.",
  errorUnconfigured: "Manjkajo nastavitve prijave. Obrnite se na podporo.",
  errorServer: "Strežnika WIFIGATE ni mogoče doseči. Poskusite znova.",
  errorSessionExpired: "Prijava je potekla. Prijavite se znova.",
  errorForbidden: "Dostop ni dovoljen. Obrnite se na skrbnika sistema.",
  errorGeneric: "Prišlo je do napake. Poskusite znova.",
};
