// Sign-in page copy (/sv/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Logga in",
  heading: "Logga in på WIFIGATE",
  home: "WIFIGATE startsida",
  google: "Fortsätt med Google",
  apple: "Fortsätt med Apple",
  signingInLabel: "Loggar in",
  legal: "Genom att fortsätta godkänner du våra {terms} och vår {privacy}.",
  terms: "villkor",
  privacy: "integritetspolicy",
  chooseLanguage: "Välj språk",
  close: "Stäng",
  stagingTitle: "Lokal testmiljö",
  stagingText: "Använd simulerade Google- eller Apple-konton. Inget lösenord från leverantören behövs.",
  mfaTitle: "Verifiera med autentiseringsappen",
  mfaText: "Ange den aktuella koden från din autentiseringsapp för att slutföra inloggningen.",
  mfaFactor: "Autentiseringsapp",
  mfaCode: "Verifieringskod",
  mfaVerify: "Verifiera",
  mfaCancel: "Avbryt",
  mfaHelp: "Har du förlorat åtkomsten? Kontakta plattformens administratör för att verifiera din identitet och återställa din autentiseringsmetod.",
  authenticatorN: "Autentiseringsapp {n}",
  verifying: "Verifierar...",
  checking: "Kontrollerar din åtkomst...",
  opening: "Öppnar kontrollpanelen...",
  signingIn: "Loggar in...",
  humanReady: "Godkänt! Fortsätt nu med Google eller Apple.",
  accessUnavailable: "Det går inte att kontrollera åtkomsten just nu. Försök igen.",
  gameTitle: "Jag är inte en robot",
  gameInstruction: "Bekräfta genom att dra bilen in i den öppna grinden",
  gameFooter: "Mänsklig kontroll · WIFIGATE",
  gameKeyboard: "Bilen är i fil {lane} av 3. Piltangenterna byter fil, Enter kör.",
  gameGate: "Grind {n}, {state}",
  gateOpen: "öppen",
  gateClosed: "stängd",
  gameRetry: "Inte riktigt. Kör in i den gröna grinden.",
  gameLocked: "För många försök. Försök igen om {s} sekunder.",
  gameDone: "Verifierad. Du är inte en robot.",
  errorCancelled: "Inloggningen avbröts.",
  errorPopupBlocked: "Webbläsaren blockerade inloggningsfönstret.",
  errorInvalidCode: "Koden är felaktig eller har gått ut.",
  errorMissingCode: "Ange koden från din autentiseringsapp.",
  errorNetwork: "Det går inte att ansluta. Kontrollera din nätverksanslutning.",
  errorMfaCancelled: "Verifieringen av kontot avbröts.",
  errorMfaUnsupported: "Det här kontot har ingen autentiseringsapp som stöds.",
  errorUnverifiedEmail: "Använd den verifierade e-postadressen som din administratör har godkänt.",
  errorUnconfigured: "Inloggningsinställningarna saknas. Kontakta kundtjänst.",
  errorServer: "Det går inte att nå WIFIGATE-servern. Försök igen.",
  errorSessionExpired: "Inloggningen har gått ut. Logga in igen.",
  errorForbidden: "Åtkomst nekad. Kontakta systemadministratören.",
  errorGeneric: "Något gick fel. Försök igen.",
};
