// Sign-in page copy (/tr/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Giriş",
  heading: "WIFIGATE'e giriş yapın",
  home: "WIFIGATE ana sayfası",
  google: "Google ile devam et",
  apple: "Apple ile devam et",
  signingInLabel: "Giriş yapılıyor",
  legal: "Devam ederek {terms} ve {privacy} metinlerini kabul etmiş olursunuz.",
  terms: "Şartlar",
  privacy: "Gizlilik Politikası",
  chooseLanguage: "Dil seçin",
  close: "Kapat",
  stagingTitle: "Yerel test ortamı",
  stagingText: "Sahte Google veya Apple hesapları kullanılır. Sağlayıcı şifresi gerekmez.",
  mfaTitle: "Kimlik doğrulama uygulamasıyla doğrulama",
  mfaText: "Girişi tamamlamak için kimlik doğrulama uygulamanızdaki güncel kodu girin.",
  mfaFactor: "Kimlik doğrulama uygulaması",
  mfaCode: "Doğrulama kodu",
  mfaVerify: "Doğrula",
  mfaCancel: "İptal",
  mfaHelp: "Erişiminizi mi kaybettiniz? Kimliğinizi doğrulamak ve doğrulama yönteminizi kurtarmak için platform yöneticisine başvurun.",
  authenticatorN: "Kimlik doğrulama uygulaması {n}",
  verifying: "Doğrulanıyor...",
  checking: "Erişiminiz kontrol ediliyor...",
  opening: "Kontrol paneli açılıyor...",
  signingIn: "Giriş yapılıyor...",
  humanReady: "Doğrulamayı geçtiniz. Şimdi Google veya Apple ile devam edin.",
  accessUnavailable: "Erişim şu anda kontrol edilemiyor. Lütfen tekrar deneyin.",
  gameTitle: "Ben robot değilim",
  gameInstruction: "Onaylamak için arabayı açık kapıya sürükleyin",
  gameFooter: "İnsan doğrulaması · WIFIGATE",
  gameKeyboard: "Araba 3 şeritten {lane}. şeritte. Ok tuşları şerit değiştirir, Enter ile sürülür.",
  gameGate: "Kapı {n}, {state}",
  gateOpen: "açık",
  gateClosed: "kapalı",
  gameRetry: "Tam olmadı. Yeşil kapıya girin.",
  gameLocked: "Çok fazla deneme yapıldı. {s} saniye sonra tekrar deneyin.",
  gameDone: "Doğrulandı. Robot değilsiniz.",
  errorCancelled: "Giriş iptal edildi.",
  errorPopupBlocked: "Tarayıcı giriş penceresini engelledi.",
  errorInvalidCode: "Kod hatalı veya süresi dolmuş.",
  errorMissingCode: "Kimlik doğrulama uygulamanızdaki kodu girin.",
  errorNetwork: "Bağlantı kurulamıyor. Ağ bağlantınızı kontrol edin.",
  errorMfaCancelled: "Hesap doğrulaması iptal edildi.",
  errorMfaUnsupported: "Bu hesapta desteklenen bir kimlik doğrulama uygulaması yok.",
  errorUnverifiedEmail: "Yöneticinizin onayladığı doğrulanmış e-posta adresini kullanın.",
  errorUnconfigured: "Giriş ayarları eksik. Lütfen destek ekibine başvurun.",
  errorServer: "WIFIGATE sunucusuna bağlanılamıyor. Lütfen tekrar deneyin.",
  errorSessionExpired: "Oturumunuzun süresi doldu. Tekrar giriş yapın.",
  errorForbidden: "Erişim izni yok. Sistem yöneticinize başvurun.",
  errorGeneric: "Bir sorun oluştu. Lütfen tekrar deneyin.",
};
