// Sign-in page copy (/vi/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "Đăng nhập",
  heading: "Đăng nhập vào WIFIGATE",
  home: "Trang chủ WIFIGATE",
  google: "Tiếp tục với Google",
  apple: "Tiếp tục với Apple",
  signingInLabel: "Đang đăng nhập",
  legal: "Khi tiếp tục, bạn đồng ý với {terms} và {privacy}.",
  terms: "Điều khoản",
  privacy: "Chính sách quyền riêng tư",
  chooseLanguage: "Chọn ngôn ngữ",
  close: "Đóng",
  stagingTitle: "Môi trường thử nghiệm cục bộ",
  stagingText: "Sử dụng tài khoản Google hoặc Apple mô phỏng. Không cần mật khẩu của nhà cung cấp.",
  mfaTitle: "Xác minh bằng ứng dụng xác thực",
  mfaText: "Nhập mã hiện tại từ ứng dụng xác thực để hoàn tất đăng nhập.",
  mfaFactor: "Ứng dụng xác thực",
  mfaCode: "Mã xác minh",
  mfaVerify: "Xác minh",
  mfaCancel: "Hủy",
  mfaHelp: "Mất quyền truy cập? Hãy liên hệ quản trị viên nền tảng để xác minh danh tính và khôi phục phương thức xác thực của bạn.",
  authenticatorN: "Ứng dụng xác thực {n}",
  verifying: "Đang xác minh...",
  checking: "Đang kiểm tra quyền truy cập của bạn...",
  opening: "Đang mở bảng điều khiển...",
  signingIn: "Đang đăng nhập...",
  humanReady: "Bạn đã vượt qua. Giờ hãy tiếp tục với Google hoặc Apple.",
  accessUnavailable: "Hiện không thể kiểm tra quyền truy cập. Vui lòng thử lại.",
  gameTitle: "Tôi không phải là người máy",
  gameInstruction: "Để xác nhận, hãy kéo xe vào cổng đang mở",
  gameFooter: "Xác minh người thật · WIFIGATE",
  gameKeyboard: "Xe ở làn {lane} trên 3. Phím mũi tên để đổi làn, Enter để chạy.",
  gameGate: "Cổng {n}, {state}",
  gateOpen: "đang mở",
  gateClosed: "đang đóng",
  gameRetry: "Chưa đúng. Hãy lái vào cổng màu xanh lá.",
  gameLocked: "Quá nhiều lần thử. Hãy thử lại sau {s} giây.",
  gameDone: "Đã xác minh. Bạn không phải là người máy.",
  errorCancelled: "Đã hủy đăng nhập.",
  errorPopupBlocked: "Trình duyệt đã chặn cửa sổ đăng nhập.",
  errorInvalidCode: "Mã không đúng hoặc đã hết hạn.",
  errorMissingCode: "Nhập mã từ ứng dụng xác thực.",
  errorNetwork: "Không thể kết nối. Hãy kiểm tra kết nối mạng.",
  errorMfaCancelled: "Đã hủy xác minh tài khoản.",
  errorMfaUnsupported: "Tài khoản này không có ứng dụng xác thực được hỗ trợ.",
  errorUnverifiedEmail: "Hãy dùng địa chỉ email đã xác minh được quản trị viên phê duyệt.",
  errorUnconfigured: "Thiếu cài đặt đăng nhập. Vui lòng liên hệ bộ phận hỗ trợ.",
  errorServer: "Không thể kết nối với máy chủ WIFIGATE. Vui lòng thử lại.",
  errorSessionExpired: "Phiên đăng nhập đã hết hạn. Hãy đăng nhập lại.",
  errorForbidden: "Không được phép truy cập. Hãy liên hệ quản trị viên hệ thống.",
  errorGeneric: "Đã xảy ra lỗi. Vui lòng thử lại.",
};
