// Sign-in page copy (/zh-hans/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "登录",
  heading: "登录 WIFIGATE",
  home: "WIFIGATE 首页",
  google: "通过 Google 继续",
  apple: "通过 Apple 继续",
  signingInLabel: "正在登录",
  legal: "继续即表示您同意{terms}和{privacy}。",
  terms: "条款",
  privacy: "隐私政策",
  chooseLanguage: "选择语言",
  close: "关闭",
  stagingTitle: "本地测试环境",
  stagingText: "使用模拟的 Google 或 Apple 账号，无需提供方密码。",
  mfaTitle: "通过身份验证器应用验证",
  mfaText: "请输入身份验证器应用中的当前验证码以完成登录。",
  mfaFactor: "身份验证器应用",
  mfaCode: "验证码",
  mfaVerify: "验证",
  mfaCancel: "取消",
  mfaHelp: "无法访问？请联系平台管理员验证身份并恢复验证方式。",
  authenticatorN: "身份验证器应用 {n}",
  verifying: "正在验证...",
  checking: "正在检查您的访问权限...",
  opening: "正在打开控制面板...",
  signingIn: "正在登录...",
  humanReady: "验证已通过。现在可以通过 Google 或 Apple 继续。",
  accessUnavailable: "暂时无法检查访问权限，请重试。",
  gameTitle: "我不是机器人",
  gameInstruction: "请将汽车拖入打开的闸门以确认",
  gameFooter: "人机验证 · WIFIGATE",
  gameKeyboard: "汽车位于第 {lane} 条车道（共 3 条）。方向键切换车道，按 Enter 行驶。",
  gameGate: "闸门 {n}，{state}",
  gateOpen: "已打开",
  gateClosed: "已关闭",
  gameRetry: "差一点。请驶入绿色闸门。",
  gameLocked: "尝试次数过多，请在 {s} 秒后重试。",
  gameDone: "验证成功。您不是机器人。",
  errorCancelled: "登录已取消。",
  errorPopupBlocked: "浏览器拦截了登录窗口。",
  errorInvalidCode: "验证码错误或已过期。",
  errorMissingCode: "请输入身份验证器应用中的验证码。",
  errorNetwork: "无法连接，请检查网络连接。",
  errorMfaCancelled: "账号验证已取消。",
  errorMfaUnsupported: "此账号没有受支持的身份验证器应用。",
  errorUnverifiedEmail: "请使用经管理员批准的已验证邮箱。",
  errorUnconfigured: "缺少登录设置，请联系支持团队。",
  errorServer: "无法连接到 WIFIGATE 服务器，请重试。",
  errorSessionExpired: "会话已过期，请重新登录。",
  errorForbidden: "无访问权限，请联系系统管理员。",
  errorGeneric: "出了点问题，请重试。",
};
