// Sign-in page copy (/zh-hant/login/). Same keys as he.mjs, the source.
export default {
  pageTitle: "登入",
  heading: "登入 WIFIGATE",
  home: "WIFIGATE 首頁",
  google: "透過 Google 繼續",
  apple: "透過 Apple 繼續",
  signingInLabel: "正在登入",
  legal: "繼續即表示您同意{terms}及{privacy}。",
  terms: "條款",
  privacy: "隱私權政策",
  chooseLanguage: "選擇語言",
  close: "關閉",
  stagingTitle: "本機測試環境",
  stagingText: "使用模擬的 Google 或 Apple 帳戶，不需要提供者密碼。",
  mfaTitle: "透過驗證器應用程式驗證",
  mfaText: "請輸入驗證器應用程式中的目前驗證碼以完成登入。",
  mfaFactor: "驗證器應用程式",
  mfaCode: "驗證碼",
  mfaVerify: "驗證",
  mfaCancel: "取消",
  mfaHelp: "無法存取？請聯絡平台管理員驗證身分並復原驗證方式。",
  authenticatorN: "驗證器應用程式 {n}",
  verifying: "正在驗證...",
  checking: "正在檢查您的存取權限...",
  opening: "正在開啟控制面板...",
  signingIn: "正在登入...",
  humanReady: "驗證已通過。現在可以透過 Google 或 Apple 繼續。",
  accessUnavailable: "目前無法檢查存取權限，請再試一次。",
  gameTitle: "我不是機器人",
  gameInstruction: "請將汽車拖進開啟的閘門以確認",
  gameFooter: "真人驗證 · WIFIGATE",
  gameKeyboard: "汽車位於第 {lane} 車道（共 3 條）。方向鍵切換車道，按 Enter 行駛。",
  gameGate: "閘門 {n}，{state}",
  gateOpen: "已開啟",
  gateClosed: "已關閉",
  gameRetry: "差一點。請駛入綠色閘門。",
  gameLocked: "嘗試次數過多，請在 {s} 秒後再試一次。",
  gameDone: "驗證成功。您不是機器人。",
  errorCancelled: "登入已取消。",
  errorPopupBlocked: "瀏覽器封鎖了登入視窗。",
  errorInvalidCode: "驗證碼錯誤或已過期。",
  errorMissingCode: "請輸入驗證器應用程式中的驗證碼。",
  errorNetwork: "無法連線，請檢查網路連線。",
  errorMfaCancelled: "帳戶驗證已取消。",
  errorMfaUnsupported: "此帳戶沒有支援的驗證器應用程式。",
  errorUnverifiedEmail: "請使用經管理員核准的已驗證電子郵件地址。",
  errorUnconfigured: "缺少登入設定，請聯絡支援團隊。",
  errorServer: "無法連線到 WIFIGATE 伺服器，請再試一次。",
  errorSessionExpired: "工作階段已過期，請重新登入。",
  errorForbidden: "沒有存取權限，請聯絡系統管理員。",
  errorGeneric: "發生錯誤，請再試一次。",
};
