// scripts/niche-content.mjs
// Centralized content + metadata model for the dedicated niche landing pages.
//
// Only the 8 homepage niches get a dedicated page. The page reuses existing
// localized copy where possible (APPLICATION_STORIES, APPLICATION_STORY_UI,
// translations.contact/footer/nav/applications) and layers a small amount of
// niche-page "chrome" (section titles + a security-soft comparison table) on
// top. New per-locale strings live in NICHE_CHROME; bespoke hero/SEO copy for
// the primary locales lives in NICHE_OVERRIDES.
//
// Slugs stay in English across every locale. URLs:
//   English: /<slug>/
//   Others : /<locale>/<slug>/

export const NICHE_DEFINITIONS = [
  { key: "hotels", legacyKey: "where-story-hotels", slug: "hotels", storyKey: "hotels" },
  { key: "roller-shutters", legacyKey: "where-story-roller-shutters", slug: "roller-shutters", storyKey: "rollerShutters" },
  { key: "residential-complexes", legacyKey: "where-story-residential-complexes", slug: "residential-complexes", storyKey: "residentialComplexes" },
  { key: "private-homes", legacyKey: "where-story-private-homes", slug: "private-homes", storyKey: "privateHomes" },
  { key: "electric-gates", legacyKey: "where-story-electric-gates", slug: "electric-gates", storyKey: "electricGates" },
  { key: "office-buildings", legacyKey: "where-story-office-buildings", slug: "office-buildings", storyKey: "officeBuildings" },
  { key: "sports-facilities", legacyKey: "where-story-sports-facilities", slug: "sports-facilities", storyKey: "sportsFacilities" },
  { key: "magnetic-locks", legacyKey: "where-story-magnetic-locks", slug: "magnetic-locks", storyKey: "magneticLocks" },
];

export const NICHE_STORY_KEYS = NICHE_DEFINITIONS.map((niche) => niche.storyKey);

// Per-locale niche-page chrome. The build falls back to the English entry for
// any field/locale that is missing, so partial coverage never breaks a build.
// The comparison rows are generic (reused across all niches) and use the
// security-soft positioning requested by the brief.
export const NICHE_CHROME = {
  en: {
    eyebrow: "WIFIGATE use case",
    problemTitle: "The problem today",
    betterTitle: "Why WIFIGATE is better",
    benefitsTitle: "Key benefits",
    comparisonTitle: "Compared to traditional access",
    comparisonLead: "How everyday access changes when control moves to the app.",
    headTraditional: "Traditional methods",
    headWifigate: "With WIFIGATE",
    rows: [
      { t: "Keys, remotes, or shared codes that can be lost, copied, or passed around", w: "App-based access you grant and revoke from your phone" },
      { t: "Exposed outdoor switches or keypads at the entry point", w: "Control moved indoors to reduce exposed access points" },
      { t: "No clear record of who opened the entrance, or when", w: "Access history for better visibility and accountability" },
      { t: "Hard to give short-term access to guests, staff, or vendors", w: "Time-limited invites that expire automatically" },
    ],
    videoTitle: "See WIFIGATE in action",
    benefitsLeadLabel: "The bottom line",
    backLabel: "Explore all use cases",
    homeLabel: "Home",
  },
  he: {
    eyebrow: "תרחיש שימוש של WIFIGATE",
    problemTitle: "הבעיה היום",
    betterTitle: "למה WIFIGATE עדיפה",
    benefitsTitle: "יתרונות עיקריים",
    comparisonTitle: "בהשוואה לשיטות הגישה המסורתיות",
    comparisonLead: "איך הגישה היומיומית משתנה כשהשליטה עוברת לאפליקציה.",
    headTraditional: "שיטות מסורתיות",
    headWifigate: "עם WIFIGATE",
    rows: [
      { t: "מפתחות, שלטים או קודים משותפים שעלולים לאבד, להעתיק או לעבור הלאה", w: "גישה מתוך האפליקציה שאתם מעניקים ומבטלים מהטלפון" },
      { t: "מתגים או קודנים חשופים בנקודת הכניסה החיצונית", w: "שליטה שעוברת פנימה ומצמצמת נקודות גישה חשופות" },
      { t: "אין תיעוד ברור של מי פתח את הכניסה ומתי", w: "היסטוריית גישה לשקיפות ולאחריותיות טובות יותר" },
      { t: "קשה להעניק גישה זמנית לאורחים, לעובדים או לספקים", w: "הזמנות מוגבלות בזמן שפגות אוטומטית" },
    ],
    videoTitle: "ראו את WIFIGATE בפעולה",
    benefitsLeadLabel: "השורה התחתונה",
    backLabel: "כל תרחישי השימוש",
    homeLabel: "דף הבית",
  },
  es: {
    eyebrow: "Caso de uso de WIFIGATE",
    problemTitle: "El problema actual",
    betterTitle: "Por qué WIFIGATE es mejor",
    benefitsTitle: "Beneficios clave",
    comparisonTitle: "Frente a los métodos de acceso tradicionales",
    comparisonLead: "Cómo cambia el acceso diario cuando el control pasa a la app.",
    headTraditional: "Métodos tradicionales",
    headWifigate: "Con WIFIGATE",
    rows: [
      { t: "Llaves, mandos o códigos compartidos que se pueden perder, copiar o ceder", w: "Acceso desde la app que concedes y revocas desde el teléfono" },
      { t: "Interruptores o teclados expuestos en el punto de entrada", w: "Control trasladado al interior para reducir los puntos de acceso expuestos" },
      { t: "Sin un registro claro de quién abrió la entrada, ni cuándo", w: "Historial de accesos para más visibilidad y control" },
      { t: "Difícil dar acceso temporal a invitados, personal o proveedores", w: "Invitaciones con tiempo limitado que caducan automáticamente" },
    ],
    videoTitle: "Mira WIFIGATE en acción",
    benefitsLeadLabel: "En resumen",
    backLabel: "Ver todos los casos de uso",
    homeLabel: "Inicio",
  },
  fr: {
    eyebrow: "Cas d'usage WIFIGATE",
    problemTitle: "Le problème actuel",
    betterTitle: "Pourquoi WIFIGATE est meilleur",
    benefitsTitle: "Avantages clés",
    comparisonTitle: "Face aux méthodes d'accès traditionnelles",
    comparisonLead: "Comment l'accès au quotidien change quand le contrôle passe sur l'app.",
    headTraditional: "Méthodes traditionnelles",
    headWifigate: "Avec WIFIGATE",
    rows: [
      { t: "Clés, télécommandes ou codes partagés qui se perdent, se copient ou circulent", w: "Un accès via l'app que vous accordez et révoquez depuis votre téléphone" },
      { t: "Interrupteurs ou claviers exposés au point d'entrée", w: "Le contrôle ramené à l'intérieur pour réduire les points d'accès exposés" },
      { t: "Aucun historique clair de qui a ouvert l'entrée, ni quand", w: "Un historique d'accès pour plus de visibilité et de responsabilité" },
      { t: "Difficile d'accorder un accès court aux invités, au personnel ou aux prestataires", w: "Des invitations à durée limitée qui expirent automatiquement" },
    ],
    videoTitle: "Découvrez WIFIGATE en action",
    benefitsLeadLabel: "En bref",
    backLabel: "Voir tous les cas d'usage",
    homeLabel: "Accueil",
  },
  de: {
    eyebrow: "WIFIGATE Anwendungsfall",
    problemTitle: "Das heutige Problem",
    betterTitle: "Warum WIFIGATE besser ist",
    benefitsTitle: "Wichtigste Vorteile",
    comparisonTitle: "Im Vergleich zu klassischen Zutrittsmethoden",
    comparisonLead: "Wie sich der tägliche Zutritt ändert, wenn die Steuerung in die App wandert.",
    headTraditional: "Klassische Methoden",
    headWifigate: "Mit WIFIGATE",
    rows: [
      { t: "Schlüssel, Handsender oder geteilte Codes, die verloren, kopiert oder weitergegeben werden", w: "App-basierter Zutritt, den Sie per Telefon erteilen und entziehen" },
      { t: "Offen liegende Schalter oder Tastenfelder am Eingang", w: "Steuerung nach innen verlagert, um offene Zugangspunkte zu reduzieren" },
      { t: "Kein klarer Nachweis, wer wann den Eingang geöffnet hat", w: "Zutrittsverlauf für mehr Transparenz und Nachvollziehbarkeit" },
      { t: "Kurzfristiger Zutritt für Gäste, Personal oder Dienstleister ist umständlich", w: "Zeitlich begrenzte Einladungen, die automatisch ablaufen" },
    ],
    videoTitle: "WIFIGATE in Aktion sehen",
    benefitsLeadLabel: "Kurz gesagt",
    backLabel: "Alle Anwendungsfälle ansehen",
    homeLabel: "Start",
  },
  nl: {
    eyebrow: "WIFIGATE-toepassing",
    problemTitle: "Het probleem vandaag",
    betterTitle: "Waarom WIFIGATE beter is",
    benefitsTitle: "Belangrijkste voordelen",
    comparisonTitle: "Vergeleken met traditionele toegang",
    comparisonLead: "Hoe dagelijkse toegang verandert als de bediening naar de app gaat.",
    headTraditional: "Traditionele methoden",
    headWifigate: "Met WIFIGATE",
    rows: [
      { t: "Sleutels, afstandsbedieningen of gedeelde codes die zoekraken, gekopieerd of doorgegeven worden", w: "Toegang via de app die u vanaf uw telefoon verleent en intrekt" },
      { t: "Blootliggende schakelaars of toetsenborden bij de ingang", w: "Bediening naar binnen verplaatst om blootgestelde toegangspunten te beperken" },
      { t: "Geen duidelijk overzicht van wie de ingang opende, en wanneer", w: "Toegangsgeschiedenis voor meer inzicht en verantwoording" },
      { t: "Lastig om kortdurende toegang te geven aan gasten, personeel of leveranciers", w: "Tijdelijke uitnodigingen die automatisch verlopen" },
    ],
    videoTitle: "Zie WIFIGATE in actie",
    benefitsLeadLabel: "Kort samengevat",
    backLabel: "Alle toepassingen bekijken",
    homeLabel: "Home",
  },
  it: {
    eyebrow: "Caso d'uso WIFIGATE",
    problemTitle: "Il problema di oggi",
    betterTitle: "Perché WIFIGATE è meglio",
    benefitsTitle: "Vantaggi principali",
    comparisonTitle: "Rispetto ai metodi di accesso tradizionali",
    comparisonLead: "Come cambia l'accesso quotidiano quando il controllo passa all'app.",
    headTraditional: "Metodi tradizionali",
    headWifigate: "Con WIFIGATE",
    rows: [
      { t: "Chiavi, telecomandi o codici condivisi che si perdono, si copiano o si passano", w: "Accesso dall'app che concedi e revochi dal telefono" },
      { t: "Interruttori o tastierini esposti nel punto di ingresso", w: "Controllo spostato all'interno per ridurre i punti di accesso esposti" },
      { t: "Nessun registro chiaro di chi ha aperto l'ingresso, e quando", w: "Cronologia degli accessi per più visibilità e responsabilità" },
      { t: "Difficile dare accesso temporaneo a ospiti, personale o fornitori", w: "Inviti a tempo limitato che scadono automaticamente" },
    ],
    videoTitle: "Guarda WIFIGATE in azione",
    benefitsLeadLabel: "In sintesi",
    backLabel: "Vedi tutti i casi d'uso",
    homeLabel: "Home",
  },
  pt: {
    eyebrow: "Caso de uso do WIFIGATE",
    problemTitle: "O problema atual",
    betterTitle: "Porque o WIFIGATE é melhor",
    benefitsTitle: "Principais benefícios",
    comparisonTitle: "Em comparação com os acessos tradicionais",
    comparisonLead: "Como o acesso do dia a dia muda quando o controlo passa para a app.",
    headTraditional: "Métodos tradicionais",
    headWifigate: "Com o WIFIGATE",
    rows: [
      { t: "Chaves, comandos ou códigos partilhados que se perdem, copiam ou passam adiante", w: "Acesso pela app que concede e revoga a partir do telemóvel" },
      { t: "Interruptores ou teclados expostos no ponto de entrada", w: "Controlo movido para dentro para reduzir os pontos de acesso expostos" },
      { t: "Sem um registo claro de quem abriu a entrada, nem quando", w: "Histórico de acessos para mais visibilidade e responsabilização" },
      { t: "Difícil dar acesso temporário a convidados, pessoal ou fornecedores", w: "Convites com tempo limitado que expiram automaticamente" },
    ],
    videoTitle: "Veja o WIFIGATE em ação",
    benefitsLeadLabel: "Em resumo",
    backLabel: "Ver todos os casos de uso",
    homeLabel: "Início",
  },
  pl: {
    eyebrow: "Zastosowanie WIFIGATE",
    problemTitle: "Dzisiejszy problem",
    betterTitle: "Dlaczego WIFIGATE jest lepszy",
    benefitsTitle: "Najważniejsze korzyści",
    comparisonTitle: "W porównaniu z tradycyjnym dostępem",
    comparisonLead: "Jak zmienia się codzienny dostęp, gdy sterowanie przenosi się do aplikacji.",
    headTraditional: "Metody tradycyjne",
    headWifigate: "Z WIFIGATE",
    rows: [
      { t: "Klucze, piloty lub współdzielone kody, które można zgubić, skopiować lub przekazać", w: "Dostęp z aplikacji, który nadajesz i cofasz z telefonu" },
      { t: "Odsłonięte włączniki lub klawiatury w punkcie wejścia", w: "Sterowanie przeniesione do środka, by ograniczyć odsłonięte punkty dostępu" },
      { t: "Brak jasnego zapisu, kto i kiedy otworzył wejście", w: "Historia dostępu dla większej przejrzystości i odpowiedzialności" },
      { t: "Trudno nadać krótki dostęp gościom, personelowi lub dostawcom", w: "Zaproszenia czasowe, które wygasają automatycznie" },
    ],
    videoTitle: "Zobacz WIFIGATE w akcji",
    benefitsLeadLabel: "W skrócie",
    backLabel: "Zobacz wszystkie zastosowania",
    homeLabel: "Strona główna",
  },
  no: {
    eyebrow: "WIFIGATE bruksområde",
    problemTitle: "Problemet i dag",
    betterTitle: "Hvorfor WIFIGATE er bedre",
    benefitsTitle: "Viktigste fordeler",
    comparisonTitle: "Sammenlignet med tradisjonell adgang",
    comparisonLead: "Hvordan daglig adgang endrer seg når styringen flyttes til appen.",
    headTraditional: "Tradisjonelle metoder",
    headWifigate: "Med WIFIGATE",
    rows: [
      { t: "Nøkler, fjernkontroller eller delte koder som kan mistes, kopieres eller gis videre", w: "App-basert adgang du gir og trekker tilbake fra telefonen" },
      { t: "Eksponerte brytere eller tastaturer ved inngangen", w: "Styring flyttet innendørs for å redusere eksponerte adgangspunkter" },
      { t: "Ingen tydelig oversikt over hvem som åpnet inngangen, og når", w: "Adgangshistorikk for bedre oversikt og ansvarlighet" },
      { t: "Vanskelig å gi kortvarig adgang til gjester, ansatte eller leverandører", w: "Tidsbegrensede invitasjoner som utløper automatisk" },
    ],
    videoTitle: "Se WIFIGATE i praksis",
    benefitsLeadLabel: "Kort fortalt",
    backLabel: "Se alle bruksområder",
    homeLabel: "Hjem",
  },
  cs: {
    eyebrow: "Využití WIFIGATE",
    problemTitle: "Dnešní problém",
    betterTitle: "Proč je WIFIGATE lepší",
    benefitsTitle: "Klíčové přínosy",
    comparisonTitle: "Ve srovnání s tradičním přístupem",
    comparisonLead: "Jak se mění každodenní přístup, když ovládání přejde do aplikace.",
    headTraditional: "Tradiční metody",
    headWifigate: "S WIFIGATE",
    rows: [
      { t: "Klíče, ovladače nebo sdílené kódy, které lze ztratit, zkopírovat či předat dál", w: "Přístup z aplikace, který udělíte a odeberete z telefonu" },
      { t: "Odhalené vypínače nebo klávesnice u vchodu", w: "Ovládání přesunuté dovnitř, aby se omezily odhalené přístupové body" },
      { t: "Žádný jasný záznam o tom, kdo a kdy vchod otevřel", w: "Historie přístupů pro lepší přehled a odpovědnost" },
      { t: "Obtížné udělit krátkodobý přístup hostům, personálu nebo dodavatelům", w: "Časově omezené pozvánky, které automaticky vyprší" },
    ],
    videoTitle: "Podívejte se na WIFIGATE v akci",
    benefitsLeadLabel: "Ve zkratce",
    backLabel: "Zobrazit všechna využití",
    homeLabel: "Domů",
  },
  ru: {
    eyebrow: "Сценарий применения WIFIGATE",
    problemTitle: "Проблема сегодня",
    betterTitle: "Почему WIFIGATE лучше",
    benefitsTitle: "Ключевые преимущества",
    comparisonTitle: "В сравнении с традиционным доступом",
    comparisonLead: "Как меняется повседневный доступ, когда управление переходит в приложение.",
    headTraditional: "Традиционные методы",
    headWifigate: "С WIFIGATE",
    rows: [
      { t: "Ключи, пульты или общие коды, которые можно потерять, скопировать или передать", w: "Доступ из приложения, который вы выдаёте и отзываете с телефона" },
      { t: "Открытые переключатели или клавиатуры на входе", w: "Управление перенесено внутрь, чтобы сократить открытые точки доступа" },
      { t: "Нет чёткой записи о том, кто и когда открыл вход", w: "История доступа для большей прозрачности и контроля" },
      { t: "Сложно выдать кратковременный доступ гостям, персоналу или подрядчикам", w: "Приглашения с ограничением по времени, истекающие автоматически" },
    ],
    videoTitle: "Посмотрите WIFIGATE в действии",
    benefitsLeadLabel: "Коротко о главном",
    backLabel: "Все сценарии применения",
    homeLabel: "Главная",
  },
  uk: {
    eyebrow: "Сценарій застосування WIFIGATE",
    problemTitle: "Проблема сьогодні",
    betterTitle: "Чому WIFIGATE кращий",
    benefitsTitle: "Ключові переваги",
    comparisonTitle: "Порівняно з традиційним доступом",
    comparisonLead: "Як змінюється щоденний доступ, коли керування переходить у застосунок.",
    headTraditional: "Традиційні методи",
    headWifigate: "З WIFIGATE",
    rows: [
      { t: "Ключі, пульти чи спільні коди, які можна загубити, скопіювати або передати", w: "Доступ із застосунку, який ви надаєте й скасовуєте з телефона" },
      { t: "Відкриті вимикачі або клавіатури на вході", w: "Керування перенесене всередину, щоб зменшити відкриті точки доступу" },
      { t: "Немає чіткого запису, хто й коли відчинив вхід", w: "Історія доступу для кращої прозорості та відповідальності" },
      { t: "Важко надати короткочасний доступ гостям, персоналу чи підрядникам", w: "Запрошення з обмеженим часом, що завершуються автоматично" },
    ],
    videoTitle: "Подивіться WIFIGATE у дії",
    benefitsLeadLabel: "Коротко",
    backLabel: "Усі сценарії застосування",
    homeLabel: "Головна",
  },
  tr: {
    eyebrow: "WIFIGATE kullanım senaryosu",
    problemTitle: "Bugünkü sorun",
    betterTitle: "WIFIGATE neden daha iyi",
    benefitsTitle: "Temel avantajlar",
    comparisonTitle: "Geleneksel erişime kıyasla",
    comparisonLead: "Kontrol uygulamaya geçtiğinde günlük erişim nasıl değişir.",
    headTraditional: "Geleneksel yöntemler",
    headWifigate: "WIFIGATE ile",
    rows: [
      { t: "Kaybolabilen, kopyalanabilen veya el değiştirebilen anahtarlar, kumandalar veya paylaşılan kodlar", w: "Telefonunuzdan verip iptal ettiğiniz uygulama tabanlı erişim" },
      { t: "Giriş noktasında açıkta duran anahtarlar veya tuş takımları", w: "Açık erişim noktalarını azaltmak için içeri taşınan kontrol" },
      { t: "Girişi kimin, ne zaman açtığına dair net bir kayıt yok", w: "Daha iyi görünürlük ve hesap verebilirlik için erişim geçmişi" },
      { t: "Misafirlere, personele veya tedarikçilere kısa süreli erişim vermek zor", w: "Otomatik olarak sona eren süreli davetler" },
    ],
    videoTitle: "WIFIGATE'i iş başında görün",
    benefitsLeadLabel: "Özetle",
    backLabel: "Tüm kullanım senaryoları",
    homeLabel: "Ana sayfa",
  },
  ar: {
    eyebrow: "حالة استخدام WIFIGATE",
    problemTitle: "المشكلة اليوم",
    betterTitle: "لماذا WIFIGATE أفضل",
    benefitsTitle: "أهم المزايا",
    comparisonTitle: "مقارنة بطرق الوصول التقليدية",
    comparisonLead: "كيف يتغير الوصول اليومي عندما ينتقل التحكم إلى التطبيق.",
    headTraditional: "الطرق التقليدية",
    headWifigate: "مع WIFIGATE",
    rows: [
      { t: "مفاتيح أو أجهزة تحكم أو أكواد مشتركة قد تُفقد أو تُنسخ أو تُتداول", w: "وصول عبر التطبيق تمنحه وتلغيه من هاتفك" },
      { t: "مفاتيح أو لوحات أرقام مكشوفة عند نقطة الدخول", w: "نقل التحكم إلى الداخل لتقليل نقاط الوصول المكشوفة" },
      { t: "لا يوجد سجل واضح لمن فتح المدخل ومتى", w: "سجل وصول لمزيد من الوضوح والمساءلة" },
      { t: "من الصعب منح وصول قصير للضيوف أو الموظفين أو المورّدين", w: "دعوات محدودة بوقت تنتهي تلقائيًا" },
    ],
    videoTitle: "شاهد WIFIGATE أثناء العمل",
    benefitsLeadLabel: "باختصار",
    backLabel: "استعرض كل حالات الاستخدام",
    homeLabel: "الرئيسية",
  },
  hi: {
    eyebrow: "WIFIGATE उपयोग परिदृश्य",
    problemTitle: "आज की समस्या",
    betterTitle: "WIFIGATE बेहतर क्यों है",
    benefitsTitle: "मुख्य लाभ",
    comparisonTitle: "पारंपरिक एक्सेस की तुलना में",
    comparisonLead: "जब नियंत्रण ऐप में आता है तो रोज़मर्रा का एक्सेस कैसे बदलता है।",
    headTraditional: "पारंपरिक तरीके",
    headWifigate: "WIFIGATE के साथ",
    rows: [
      { t: "चाबियाँ, रिमोट या साझा कोड जो खो सकते हैं, कॉपी हो सकते हैं या आगे बढ़ सकते हैं", w: "ऐप-आधारित एक्सेस जिसे आप फ़ोन से देते और रद्द करते हैं" },
      { t: "प्रवेश बिंदु पर खुले स्विच या कीपैड", w: "खुले एक्सेस बिंदुओं को घटाने के लिए नियंत्रण अंदर लाया गया" },
      { t: "किसने और कब प्रवेश खोला, इसका स्पष्ट रिकॉर्ड नहीं", w: "बेहतर दृश्यता और जवाबदेही के लिए एक्सेस इतिहास" },
      { t: "मेहमानों, स्टाफ़ या वेंडर को थोड़ी देर का एक्सेस देना कठिन", w: "समय-सीमित निमंत्रण जो अपने-आप समाप्त हो जाते हैं" },
    ],
    videoTitle: "WIFIGATE को काम करते देखें",
    benefitsLeadLabel: "संक्षेप में",
    backLabel: "सभी उपयोग परिदृश्य देखें",
    homeLabel: "होम",
  },
  bn: {
    eyebrow: "WIFIGATE ব্যবহারের ক্ষেত্র",
    problemTitle: "আজকের সমস্যা",
    betterTitle: "WIFIGATE কেন ভালো",
    benefitsTitle: "মূল সুবিধা",
    comparisonTitle: "প্রচলিত অ্যাক্সেসের তুলনায়",
    comparisonLead: "নিয়ন্ত্রণ অ্যাপে এলে প্রতিদিনের অ্যাক্সেস কীভাবে বদলে যায়।",
    headTraditional: "প্রচলিত পদ্ধতি",
    headWifigate: "WIFIGATE দিয়ে",
    rows: [
      { t: "চাবি, রিমোট বা শেয়ার করা কোড যা হারানো, কপি বা হাতবদল হতে পারে", w: "অ্যাপ-ভিত্তিক অ্যাক্সেস যা আপনি ফোন থেকে দেন ও বাতিল করেন" },
      { t: "প্রবেশপথে খোলা সুইচ বা কীপ্যাড", w: "উন্মুক্ত অ্যাক্সেস পয়েন্ট কমাতে নিয়ন্ত্রণ ভেতরে আনা হয়েছে" },
      { t: "কে কখন প্রবেশপথ খুলেছে তার স্পষ্ট রেকর্ড নেই", w: "ভালো স্বচ্ছতা ও জবাবদিহির জন্য অ্যাক্সেস ইতিহাস" },
      { t: "অতিথি, কর্মী বা সরবরাহকারীকে স্বল্পমেয়াদি অ্যাক্সেস দেওয়া কঠিন", w: "সময়সীমাবদ্ধ আমন্ত্রণ যা স্বয়ংক্রিয়ভাবে শেষ হয়" },
    ],
    videoTitle: "WIFIGATE কাজ করতে দেখুন",
    benefitsLeadLabel: "সংক্ষেপে",
    backLabel: "সব ব্যবহারের ক্ষেত্র দেখুন",
    homeLabel: "হোম",
  },
  mr: {
    eyebrow: "WIFIGATE वापर परिस्थिती",
    problemTitle: "आजची समस्या",
    betterTitle: "WIFIGATE अधिक चांगले का",
    benefitsTitle: "मुख्य फायदे",
    comparisonTitle: "पारंपरिक प्रवेशाच्या तुलनेत",
    comparisonLead: "नियंत्रण अ‍ॅपकडे गेल्यावर रोजचा प्रवेश कसा बदलतो.",
    headTraditional: "पारंपरिक पद्धती",
    headWifigate: "WIFIGATE सह",
    rows: [
      { t: "किल्ल्या, रिमोट किंवा सामायिक कोड जे हरवू, कॉपी होऊ किंवा पुढे जाऊ शकतात", w: "अ‍ॅप-आधारित प्रवेश जो तुम्ही फोनवरून देता आणि रद्द करता" },
      { t: "प्रवेश ठिकाणी उघडे स्विच किंवा कीपॅड", w: "उघडे प्रवेश बिंदू कमी करण्यासाठी नियंत्रण आत आणले" },
      { t: "प्रवेश कोणी आणि केव्हा उघडला याची स्पष्ट नोंद नाही", w: "अधिक दृश्यमानता आणि जबाबदारीसाठी प्रवेश इतिहास" },
      { t: "पाहुणे, कर्मचारी किंवा पुरवठादारांना अल्पकालीन प्रवेश देणे कठीण", w: "वेळ-मर्यादित आमंत्रणे जी आपोआप संपतात" },
    ],
    videoTitle: "WIFIGATE कृतीत पाहा",
    benefitsLeadLabel: "थोडक्यात",
    backLabel: "सर्व वापर परिस्थिती पाहा",
    homeLabel: "मुख्यपृष्ठ",
  },
  te: {
    eyebrow: "WIFIGATE వినియోగ సందర్భం",
    problemTitle: "నేటి సమస్య",
    betterTitle: "WIFIGATE ఎందుకు మెరుగు",
    benefitsTitle: "ముఖ్య ప్రయోజనాలు",
    comparisonTitle: "సంప్రదాయ యాక్సెస్‌తో పోలిస్తే",
    comparisonLead: "నియంత్రణ యాప్‌కు మారినప్పుడు రోజువారీ యాక్సెస్ ఎలా మారుతుంది.",
    headTraditional: "సంప్రదాయ పద్ధతులు",
    headWifigate: "WIFIGATEతో",
    rows: [
      { t: "పోగొట్టుకోగల, కాపీ చేయగల లేదా చేతులు మారే తాళాలు, రిమోట్లు లేదా షేర్ చేసిన కోడ్‌లు", w: "మీ ఫోన్ నుండి ఇచ్చి రద్దు చేసే యాప్ ఆధారిత యాక్సెస్" },
      { t: "ప్రవేశ స్థానంలో బహిర్గత స్విచ్‌లు లేదా కీప్యాడ్‌లు", w: "బహిర్గత యాక్సెస్ పాయింట్లను తగ్గించేందుకు నియంత్రణ లోపలికి" },
      { t: "ప్రవేశాన్ని ఎవరు ఎప్పుడు తెరిచారో స్పష్టమైన రికార్డు లేదు", w: "మెరుగైన దృశ్యత, జవాబుదారీతనం కోసం యాక్సెస్ చరిత్ర" },
      { t: "అతిథులకు, సిబ్బందికి లేదా విక్రేతలకు స్వల్పకాలిక యాక్సెస్ ఇవ్వడం కష్టం", w: "ఆటోమేటిక్‌గా ముగిసే సమయ-పరిమిత ఆహ్వానాలు" },
    ],
    videoTitle: "WIFIGATE పనిచేయడం చూడండి",
    benefitsLeadLabel: "సంక్షిప్తంగా",
    backLabel: "అన్ని వినియోగ సందర్భాలు చూడండి",
    homeLabel: "హోమ్",
  },
  "zh-Hans": {
    eyebrow: "WIFIGATE 应用场景",
    problemTitle: "当下的痛点",
    betterTitle: "为什么 WIFIGATE 更好",
    benefitsTitle: "核心优势",
    comparisonTitle: "对比传统门禁方式",
    comparisonLead: "当控制权转移到应用后，日常进出会如何改变。",
    headTraditional: "传统方式",
    headWifigate: "使用 WIFIGATE",
    rows: [
      { t: "钥匙、遥控器或共享密码，容易丢失、复制或转手", w: "通过手机授予和撤销的应用门禁" },
      { t: "入口处暴露在外的开关或键盘", w: "将控制移至室内，减少暴露的进出点" },
      { t: "无法清楚记录谁在何时开门", w: "访问记录，带来更好的可见性与责任追溯" },
      { t: "难以为访客、员工或供应商提供临时通行", w: "限时邀请，到期自动失效" },
    ],
    videoTitle: "观看 WIFIGATE 实际演示",
    benefitsLeadLabel: "一句话总结",
    backLabel: "查看所有应用场景",
    homeLabel: "首页",
  },
  "zh-Hant": {
    eyebrow: "WIFIGATE 應用情境",
    problemTitle: "當前的痛點",
    betterTitle: "為什麼 WIFIGATE 更好",
    benefitsTitle: "核心優勢",
    comparisonTitle: "對比傳統門禁方式",
    comparisonLead: "當控制權移至應用程式後，日常進出會如何改變。",
    headTraditional: "傳統方式",
    headWifigate: "使用 WIFIGATE",
    rows: [
      { t: "鑰匙、遙控器或共用密碼，容易遺失、複製或轉手", w: "透過手機授予與撤銷的應用門禁" },
      { t: "入口處外露的開關或鍵盤", w: "將控制移至室內，減少外露的進出點" },
      { t: "無法清楚記錄誰在何時開門", w: "存取紀錄，帶來更好的可見性與責任追溯" },
      { t: "難以為訪客、員工或供應商提供臨時通行", w: "限時邀請，到期自動失效" },
    ],
    videoTitle: "觀看 WIFIGATE 實際演示",
    benefitsLeadLabel: "一句話總結",
    backLabel: "查看所有應用情境",
    homeLabel: "首頁",
  },
  ja: {
    eyebrow: "WIFIGATE の活用シーン",
    problemTitle: "いまの課題",
    betterTitle: "WIFIGATE が優れている理由",
    benefitsTitle: "主なメリット",
    comparisonTitle: "従来の入退室との比較",
    comparisonLead: "操作がアプリに移ると、日々の入退室がどう変わるか。",
    headTraditional: "従来の方法",
    headWifigate: "WIFIGATE なら",
    rows: [
      { t: "紛失・複製・受け渡しが起こりうる鍵、リモコン、共有コード", w: "スマホで付与・取り消しできるアプリベースのアクセス" },
      { t: "入口にむき出しのスイッチやキーパッド", w: "操作を屋内に移し、露出した入口を減らす" },
      { t: "誰がいつ開けたかの明確な記録がない", w: "可視性と説明責任を高めるアクセス履歴" },
      { t: "来訪者・スタッフ・業者への一時的な入室許可が難しい", w: "自動で失効する期限付き招待" },
    ],
    videoTitle: "WIFIGATE の動作を見る",
    benefitsLeadLabel: "ひとことで言うと",
    backLabel: "すべての活用シーンを見る",
    homeLabel: "ホーム",
  },
  ko: {
    eyebrow: "WIFIGATE 활용 사례",
    problemTitle: "오늘의 문제",
    betterTitle: "WIFIGATE가 더 나은 이유",
    benefitsTitle: "핵심 이점",
    comparisonTitle: "기존 출입 방식과 비교",
    comparisonLead: "제어가 앱으로 옮겨지면 일상 출입이 어떻게 달라지는지.",
    headTraditional: "기존 방식",
    headWifigate: "WIFIGATE 사용 시",
    rows: [
      { t: "분실, 복제, 전달될 수 있는 열쇠, 리모컨, 공유 비밀번호", w: "휴대폰에서 부여하고 회수하는 앱 기반 출입" },
      { t: "출입구에 노출된 스위치나 키패드", w: "제어를 실내로 옮겨 노출된 출입 지점을 줄임" },
      { t: "누가 언제 문을 열었는지 명확한 기록이 없음", w: "가시성과 책임성을 높이는 출입 기록" },
      { t: "손님, 직원, 업체에 단기 출입을 주기 어려움", w: "자동으로 만료되는 기간 제한 초대" },
    ],
    videoTitle: "WIFIGATE 작동 모습 보기",
    benefitsLeadLabel: "한마디로",
    backLabel: "모든 활용 사례 보기",
    homeLabel: "홈",
  },
  da: {
    eyebrow: "WIFIGATE-anvendelse",
    problemTitle: "Problemet i dag",
    betterTitle: "Hvorfor WIFIGATE er bedre",
    benefitsTitle: "Vigtigste fordele",
    comparisonTitle: "Sammenlignet med traditionel adgang",
    comparisonLead: "Hvordan daglig adgang ændrer sig, når styringen flytter til appen.",
    headTraditional: "Traditionelle metoder",
    headWifigate: "Med WIFIGATE",
    rows: [
      { t: "Nøgler, fjernbetjeninger eller delte koder, der kan mistes, kopieres eller gives videre", w: "App-baseret adgang, du giver og tilbagekalder fra telefonen" },
      { t: "Eksponerede kontakter eller tastaturer ved indgangen", w: "Styring flyttet indenfor for at reducere eksponerede adgangspunkter" },
      { t: "Ingen klar registrering af, hvem der åbnede indgangen, og hvornår", w: "Adgangshistorik for bedre overblik og ansvarlighed" },
      { t: "Svært at give kortvarig adgang til gæster, personale eller leverandører", w: "Tidsbegrænsede invitationer, der udløber automatisk" },
    ],
    videoTitle: "Se WIFIGATE i aktion",
    benefitsLeadLabel: "Kort sagt",
    backLabel: "Se alle anvendelser",
    homeLabel: "Hjem",
  },
  hu: {
    eyebrow: "WIFIGATE felhasználási eset",
    problemTitle: "A mai probléma",
    betterTitle: "Miért jobb a WIFIGATE",
    benefitsTitle: "Fő előnyök",
    comparisonTitle: "A hagyományos belépéshez képest",
    comparisonLead: "Hogyan változik a napi belépés, ha a vezérlés az appba kerül.",
    headTraditional: "Hagyományos módszerek",
    headWifigate: "A WIFIGATE-tel",
    rows: [
      { t: "Kulcsok, távirányítók vagy megosztott kódok, amelyek elveszhetnek, lemásolhatók vagy továbbadhatók", w: "Appalapú belépés, amelyet telefonról ad meg és von vissza" },
      { t: "Szabadon hozzáférhető kapcsolók vagy billentyűzetek a bejáratnál", w: "A vezérlés beljebb kerül, csökkentve a kitett belépési pontokat" },
      { t: "Nincs egyértelmű nyilvántartás arról, ki és mikor nyitotta a bejáratot", w: "Belépési előzmények a jobb átláthatóságért és elszámoltathatóságért" },
      { t: "Nehéz rövid távú belépést adni vendégeknek, személyzetnek vagy beszállítóknak", w: "Időkorlátos meghívók, amelyek automatikusan lejárnak" },
    ],
    videoTitle: "Nézze meg a WIFIGATE-et működés közben",
    benefitsLeadLabel: "Röviden",
    backLabel: "Összes felhasználási eset",
    homeLabel: "Kezdőlap",
  },
};

// Bespoke hero + SEO copy for the primary locales. Falls back to the localized
// niche label + APPLICATION_STORIES pitch when an override is not provided.
export const NICHE_OVERRIDES = {
  en: {
    hotels: {
      heroHeadline: "Modern hotel access without keys, cards, or front-desk bottlenecks",
      heroSubline:
        "Give guests and staff a smoother arrival. Grant entry the moment a booking is confirmed, manage staff permissions, and let access start and end automatically around each stay.",
      metaTitle: "Hotel & Airbnb Access Control | WIFIGATE",
      metaDescription:
        "WIFIGATE gives hotels and guest accommodations app-based access for gates, barriers, and entry points. No physical keys or cards, time-limited guest access, and full control from the phone.",
    },
    rollerShutters: {
      heroHeadline: "Move roller-shutter and commercial-garage control off the wall and into the app",
      heroSubline:
        "Traditional exterior switches and shared remotes can create avoidable exposure. WIFIGATE moves the control point indoors, reduces exposed access methods, and adds app-based access with a clear access history.",
      metaTitle: "Commercial Garage & Roller Shutter Access | WIFIGATE",
      metaDescription:
        "WIFIGATE operates commercial garages and electric roller shutters from the phone. Reduce exposed outdoor switches, cut shared remotes, and gain app-based control with access history.",
    },
    residentialComplexes: {
      heroHeadline: "Building access that residents love and managers can actually control",
      heroSubline:
        "Replace shared keypad codes and copied keys with controlled, app-based entry. Residents grant guest access in seconds, and committees keep visibility over who can open the door.",
      metaTitle: "Residential Building Access Control | WIFIGATE",
      metaDescription:
        "WIFIGATE brings controlled, app-based access to residential buildings. Stop sharing keypad codes, give time-limited guest access, and manage multiple gates from one phone.",
    },
    privateHomes: {
      heroHeadline: "Open your gate from your phone and stop handing out remotes",
      heroSubline:
        "Let family in with a tap, send cleaners or guests a time-limited invite, and skip the lost-remote routine. Convenient for everyday life, with control that stays in your hands.",
      metaTitle: "Smart Gate Access for Private Homes | WIFIGATE",
      metaDescription:
        "WIFIGATE lets homeowners open gates and entries from the phone, share time-limited guest access, and reduce dependence on physical remotes and keys.",
    },
    electricGates: {
      heroHeadline: "Turn your electric gate into a simple, shareable phone-based entry",
      heroSubline:
        "Owners, residents, and guests open the gate from the phone instead of juggling remotes and keypads. Share temporary or permanent access, with auto-open for a smoother daily routine.",
      metaTitle: "Electric Gate Access Control | WIFIGATE",
      metaDescription:
        "WIFIGATE upgrades electric gates with app-based access, shareable guest invites, and auto-open. Less dependence on remotes and keypads, more control from the phone.",
    },
    officeBuildings: {
      heroHeadline: "Professional office entry for employees, visitors, and facilities teams",
      heroSubline:
        "Give staff recurring access, send visitors a temporary invite before they arrive, and let facilities manage entry cleanly from the phone, less front-desk load, a stronger first impression.",
      metaTitle: "Office Building Access Control | WIFIGATE",
      metaDescription:
        "WIFIGATE modernizes office access with app-based entry for staff and visitors, time-limited invites, and cleaner access management for facilities teams.",
    },
    sportsFacilities: {
      heroHeadline: "Fast, controlled access for members, staff, and event-day crowds",
      heroSubline:
        "Keep members and daily staff moving with smooth recurring access, while trainers, vendors, and event guests get the right permissions for the right time window.",
      metaTitle: "Sports Facility Access Control | WIFIGATE",
      metaDescription:
        "WIFIGATE helps gyms, clubs, and sports complexes manage member, staff, and visitor access from the phone, with time-limited permissions and less front-desk pressure.",
    },
    magneticLocks: {
      heroHeadline: "Smarter management for magnetic-lock doors and controlled entries",
      heroSubline:
        "Give admins, users, and guests the right level of access by role, share short-term entry that expires on its own, and reduce the pile of shared codes around the front desk.",
      metaTitle: "Magnetic Lock Access Control | WIFIGATE",
      metaDescription:
        "WIFIGATE adds role-based, app-managed control to magnetic-lock doors. Reduce shared codes, grant expiring guest access, and balance security with convenience.",
    },
  },
  he: {
    hotels: {
      heroHeadline: "גישה מודרנית למלון בלי מפתחות, כרטיסים או צוואר בקבוק בקבלה",
      heroSubline:
        "תנו לאורחים ולצוות הגעה חלקה יותר. העניקו כניסה ברגע אישור ההזמנה, נהלו הרשאות צוות, ותנו לגישה להתחיל ולהסתיים אוטומטית סביב כל שהות.",
      metaTitle: "בקרת גישה למלונות ו-Airbnb | WIFIGATE",
      metaDescription:
        "WIFIGATE מעניקה למלונות ולאתרי אירוח גישה מבוססת אפליקציה לשערים, מחסומים ונקודות כניסה, בלי מפתחות או כרטיסים, עם גישת אורח מוגבלת בזמן ושליטה מלאה מהטלפון.",
    },
    rollerShutters: {
      heroHeadline: "העבירו את השליטה בגראז' ובתריס הגלילה מהקיר אל האפליקציה",
      heroSubline:
        "מתגים חיצוניים ושלטים משותפים יכולים ליצור חשיפה מיותרת. WIFIGATE מעבירה את נקודת השליטה פנימה, מצמצמת אמצעי גישה חשופים ומוסיפה גישה מהאפליקציה עם היסטוריית גישה ברורה.",
      metaTitle: "בקרת גישה לגראז'ים ותריסי גלילה לעסקים | WIFIGATE",
      metaDescription:
        "WIFIGATE מאפשרת לפתוח ולנהל גראז'ים ותריסי גלילה לעסקים מהטלפון. צמצמו מתגים חיצוניים חשופים, הפחיתו שלטים משותפים וקבלו שליטה מהאפליקציה עם היסטוריית גישה.",
    },
    residentialComplexes: {
      heroHeadline: "גישה לבניין שהדיירים אוהבים ושהוועד באמת יכול לשלוט בה",
      heroSubline:
        "החליפו קודי קודן משותפים ומפתחות מועתקים בכניסה מבוקרת מהאפליקציה. דיירים מעניקים גישת אורח בשניות, והוועד שומר על שקיפות לגבי מי יכול לפתוח את הדלת.",
      metaTitle: "בקרת גישה לבנייני מגורים | WIFIGATE",
      metaDescription:
        "WIFIGATE מביאה גישה מבוקרת ומבוססת אפליקציה לבנייני מגורים. הפסיקו לשתף קודי קודן, העניקו גישת אורח מוגבלת בזמן ונהלו כמה שערים מטלפון אחד.",
    },
    privateHomes: {
      heroHeadline: "פתחו את השער מהטלפון והפסיקו לחלק שלטים",
      heroSubline:
        "הכניסו את המשפחה בהקשה אחת, שלחו למנקים או לאורחים הזמנה מוגבלת בזמן וחסכו את שגרת השלטים האבודים. נוחות לחיי היומיום, עם שליטה שנשארת בידיים שלכם.",
      metaTitle: "גישה חכמה לשער לבתים פרטיים | WIFIGATE",
      metaDescription:
        "WIFIGATE מאפשרת לבעלי בתים לפתוח שערים וכניסות מהטלפון, לשתף גישת אורח מוגבלת בזמן ולהפחית תלות בשלטים ובמפתחות פיזיים.",
    },
    electricGates: {
      heroHeadline: "הפכו את השער החשמלי לכניסה פשוטה מהטלפון שאפשר לשתף",
      heroSubline:
        "בעלים, דיירים ואורחים פותחים את השער מהטלפון במקום לתמרן בין שלטים וקודנים. שתפו גישה זמנית או קבועה, עם פתיחה אוטומטית לשגרה יומית חלקה יותר.",
      metaTitle: "בקרת גישה לשערים חשמליים | WIFIGATE",
      metaDescription:
        "WIFIGATE משדרגת שערים חשמליים עם גישה מהאפליקציה, הזמנות אורח לשיתוף ופתיחה אוטומטית. פחות תלות בשלטים ובקודנים, יותר שליטה מהטלפון.",
    },
    officeBuildings: {
      heroHeadline: "כניסה מקצועית למשרד לעובדים, למבקרים ולצוותי התפעול",
      heroSubline:
        "תנו לצוות גישה קבועה, שלחו למבקרים הזמנה זמנית עוד לפני שהם מגיעים, ותנו לתפעול לנהל כניסה בצורה נקייה מהטלפון, פחות עומס על הקבלה ורושם ראשוני חזק יותר.",
      metaTitle: "בקרת גישה לבנייני משרדים | WIFIGATE",
      metaDescription:
        "WIFIGATE מחדשת את הגישה למשרד עם כניסה מהאפליקציה לעובדים ולמבקרים, הזמנות מוגבלות בזמן וניהול גישה נקי יותר לצוותי התפעול.",
    },
    sportsFacilities: {
      heroHeadline: "גישה מהירה ומבוקרת לחברים, לצוות ולקהל בימי אירוע",
      heroSubline:
        "שמרו על חברים וצוות יומי בתנועה עם גישה קבועה וחלקה, בעוד מאמנים, ספקים ואורחי אירוע מקבלים את ההרשאות הנכונות לחלון הזמן הנכון.",
      metaTitle: "בקרת גישה למתקני ספורט | WIFIGATE",
      metaDescription:
        "WIFIGATE עוזרת לחדרי כושר, מועדונים ומתחמי ספורט לנהל גישת חברים, צוות ומבקרים מהטלפון, עם הרשאות מוגבלות בזמן ופחות עומס על הקבלה.",
    },
    magneticLocks: {
      heroHeadline: "ניהול חכם יותר לדלתות עם מנעול מגנטי ולכניסות מבוקרות",
      heroSubline:
        "תנו לאדמינים, למשתמשים ולאורחים את רמת הגישה הנכונה לפי תפקיד, שתפו כניסה קצרת טווח שפגה לבד, וצמצמו את ערימת הקודים המשותפים סביב הקבלה.",
      metaTitle: "בקרת גישה למנעולים מגנטיים | WIFIGATE",
      metaDescription:
        "WIFIGATE מוסיפה שליטה מבוססת תפקיד ומנוהלת מהאפליקציה לדלתות עם מנעול מגנטי. צמצמו קודים משותפים, העניקו גישת אורח שפגה לבד ואזנו בין אבטחה לנוחות.",
    },
  },
};
